// Generated by tools/generate-operations.py. Regenerate from the server contract.
import {
  activityAnalytics,
  activityDeleteEntity,
  activityEntities,
  activityHealth,
  activityIdentify,
  activityIncidents,
  activitySeries,
  activitySummary,
  activityTimeline,
  activityViews,
} from "../_internal/api/sdk.gen.js";
import type {
  ActivityAnalytics,
  ActivityAnalyticsData,
  ActivityDeleteEntityData,
  ActivityEntitiesData,
  ActivityHealth,
  ActivityHealthData,
  ActivityIncidentsData,
  ActivitySeriesData,
  ActivitySummary,
  ActivitySummaryData,
  ActivityTimelineData,
  ActivityViewsData,
  ActivityWorkspaceSeries,
  IdentifyInputBody,
  IdentifyOutputBody,
  ViewsOutputBody,
  WorkspaceEntitiesOutputBody,
  WorkspaceIncidentsOutputBody,
  WorkspaceStatusOutputBody,
  WorkspaceTimelineOutputBody,
} from "../_internal/api/types.gen.js";
import type { ResourceClient } from "./_client.js";

export class ActivityResource {
  constructor(private readonly client: ResourceClient) {}

  /** Read projected entities with their profiles; personal attributes are masked without profiles:read. `GET /workspaces/{workspaceId}/activity` */
  async entities(
    workspaceId: string,
    query: ActivityEntitiesData["query"] = {},
  ): Promise<WorkspaceEntitiesOutputBody | null> {
    return this.client.invoke(activityEntities, { path: { workspaceId }, query });
  }

  /** Distinct funnel milestones, funnel splits and client breakdowns; snapshots never count. `GET /workspaces/{workspaceId}/analytics` */
  async analytics(
    workspaceId: string,
    query: ActivityAnalyticsData["query"] = {},
  ): Promise<ActivityAnalytics | null> {
    return this.client.invoke(activityAnalytics, { path: { workspaceId }, query });
  }

  /** Erase an entity, everything linked to it and its profile, and install a replay tombstone. `DELETE /workspaces/{workspaceId}/entities/{entityType}/{entityId}` */
  async deleteEntity(
    workspaceId: string,
    entityType: string,
    entityId: string,
    query: ActivityDeleteEntityData["query"] = {},
  ): Promise<WorkspaceStatusOutputBody | null> {
    return this.client.invoke(activityDeleteEntity, {
      path: { workspaceId, entityType, entityId },
      query,
    });
  }

  /** Read storage and projection freshness, source heartbeat and undeclared attributes. `GET /workspaces/{workspaceId}/health` */
  async health(
    workspaceId: string,
    query: ActivityHealthData["query"] = {},
  ): Promise<ActivityHealth | null> {
    return this.client.invoke(activityHealth, { path: { workspaceId }, query });
  }

  /** Attach human-readable profile traits to an entity (merge; null deletes). `POST /workspaces/{workspaceId}/identify` */
  async identify(workspaceId: string, body: IdentifyInputBody): Promise<IdentifyOutputBody | null> {
    return this.client.invoke(activityIdentify, { path: { workspaceId }, body });
  }

  /** Read lifecycle incidents and recovery without duplicate notifications. `GET /workspaces/{workspaceId}/incidents` */
  async incidents(
    workspaceId: string,
    query: ActivityIncidentsData["query"] = {},
  ): Promise<WorkspaceIncidentsOutputBody | null> {
    return this.client.invoke(activityIncidents, { path: { workspaceId }, query });
  }

  /** Zero-filled time series: observations by the outcome role, distinct funnel entities by furthest stage, or source-to-view lag. `GET /workspaces/{workspaceId}/series` */
  async series(
    workspaceId: string,
    query: ActivitySeriesData["query"] = {},
  ): Promise<ActivityWorkspaceSeries | null> {
    return this.client.invoke(activitySeries, { path: { workspaceId }, query });
  }

  /** Exact entity counts per state with a 15 minute activity window. `GET /workspaces/{workspaceId}/summary` */
  async summary(
    workspaceId: string,
    query: ActivitySummaryData["query"] = {},
  ): Promise<ActivitySummary | null> {
    return this.client.invoke(activitySummary, { path: { workspaceId }, query });
  }

  /** Follow chronological source evidence; filter with ref=type:id. `GET /workspaces/{workspaceId}/timeline` */
  async timeline(
    workspaceId: string,
    query: ActivityTimelineData["query"] = {},
  ): Promise<WorkspaceTimelineOutputBody | null> {
    return this.client.invoke(activityTimeline, { path: { workspaceId }, query });
  }

  /** Aggregate the spec's declared views (KPIs, breakdowns, latency, funnels) over the active revision. `GET /workspaces/{workspaceId}/views` */
  async views(
    workspaceId: string,
    query: ActivityViewsData["query"] = {},
  ): Promise<ViewsOutputBody | null> {
    return this.client.invoke(activityViews, { path: { workspaceId }, query });
  }
}
