// Generated by tools/generate-operations.py. Regenerate from the server contract.
import {
  activityAnalytics,
  activityDeleteAgent,
  activityEntities,
  activityHealth,
  activityIncidents,
  activitySummary,
  activityTimeline,
  activityWidgets,
} from "../_internal/api/sdk.gen.js";
import type {
  ActivityAnalytics,
  ActivityAnalyticsData,
  ActivityDeleteAgentData,
  ActivityEntitiesData,
  ActivityHealthData,
  ActivityIncidentsData,
  ActivitySummaryData,
  ActivityTimelineData,
  ActivityWidgetsData,
  WorkspaceEntitiesOutputBody,
  WorkspaceIncidentsOutputBody,
  WorkspaceStatusOutputBody,
  WorkspaceTimelineOutputBody,
  WorkspaceWidgetsOutputBody,
} from "../_internal/api/types.gen.js";
import type { ResourceClient } from "./_client.js";

export class ActivityResource {
  constructor(private readonly client: ResourceClient) {}

  /** Read exact scoped business entities and concurrent operations. `GET /workspaces/{workspaceId}/activity` */
  async entities(
    workspaceId: string,
    query: ActivityEntitiesData["query"] = {},
  ): Promise<WorkspaceEntitiesOutputBody | null> {
    return this.client.invoke(activityEntities, { path: { workspaceId }, query });
  }

  /** Delete agent evidence and install a replay tombstone. `DELETE /workspaces/{workspaceId}/agents/{agentId}` */
  async deleteAgent(
    workspaceId: string,
    agentId: string,
    query: ActivityDeleteAgentData["query"] = {},
  ): Promise<WorkspaceStatusOutputBody | null> {
    return this.client.invoke(activityDeleteAgent, { path: { workspaceId, agentId }, query });
  }

  /** Distinct lifecycle milestones and client activation; snapshots never count as joins. `GET /workspaces/{workspaceId}/analytics` */
  async analytics(
    workspaceId: string,
    query: ActivityAnalyticsData["query"] = {},
  ): Promise<ActivityAnalytics | null> {
    return this.client.invoke(activityAnalytics, { path: { workspaceId }, query });
  }

  /** Read independent storage and projection freshness. `GET /workspaces/{workspaceId}/health` */
  async health(
    workspaceId: string,
    query: ActivityHealthData["query"] = {},
  ): Promise<unknown | null> {
    return this.client.invoke(activityHealth, { path: { workspaceId }, query });
  }

  /** Read lifecycle incidents and recovery without duplicate notifications. `GET /workspaces/{workspaceId}/incidents` */
  async incidents(
    workspaceId: string,
    query: ActivityIncidentsData["query"] = {},
  ): Promise<WorkspaceIncidentsOutputBody | null> {
    return this.client.invoke(activityIncidents, { path: { workspaceId }, query });
  }

  /** Exact distinct entity counts with a visible 15 minute activity window. `GET /workspaces/{workspaceId}/summary` */
  async summary(
    workspaceId: string,
    query: ActivitySummaryData["query"] = {},
  ): Promise<unknown | null> {
    return this.client.invoke(activitySummary, { path: { workspaceId }, query });
  }

  /** Follow chronological source evidence across traces. `GET /workspaces/{workspaceId}/timeline` */
  async timeline(
    workspaceId: string,
    query: ActivityTimelineData["query"] = {},
  ): Promise<WorkspaceTimelineOutputBody | null> {
    return this.client.invoke(activityTimeline, { path: { workspaceId }, query });
  }

  /** Aggregate configured business widgets over the active entity revision. `GET /workspaces/{workspaceId}/widgets` */
  async widgets(
    workspaceId: string,
    query: ActivityWidgetsData["query"] = {},
  ): Promise<WorkspaceWidgetsOutputBody | null> {
    return this.client.invoke(activityWidgets, { path: { workspaceId }, query });
  }
}
