// Generated by tools/generate-operations.py. Regenerate from the server contract.
import { observationsAccept, observationsReceipt } from "../_internal/api/sdk.gen.js";
import type {
  ActivityIngestReport,
  ActivityReceipt,
  ObservationsReceiptData,
  WorkspaceIngestInputBody,
} from "../_internal/api/types.gen.js";
import type { ResourceClient } from "./_client.js";

export class ObservationsResource {
  constructor(private readonly client: ResourceClient) {}

  /** Store an idempotent metadata-only batch; undeclared attributes are dropped and counted. `POST /workspaces/{workspaceId}/observations` */
  async accept(
    workspaceId: string,
    body: WorkspaceIngestInputBody,
  ): Promise<ActivityIngestReport | null> {
    return this.client.invoke(observationsAccept, { path: { workspaceId }, body });
  }

  /** Check storage and projection separately. `GET /workspaces/{workspaceId}/observations/{sourceEventId}` */
  async receipt(
    workspaceId: string,
    sourceEventId: string,
    query: ObservationsReceiptData["query"] = {},
  ): Promise<ActivityReceipt | null> {
    return this.client.invoke(observationsReceipt, { path: { workspaceId, sourceEventId }, query });
  }
}
