// Generated by tools/generate-operations.py. Regenerate from the server contract.
import { observationsAccept, observationsReceipt } from "../_internal/api/sdk.gen.js";
import type {
  ActivityReceipt,
  ObservationsReceiptData,
  WorkspaceIngestInputBody,
  WorkspaceIngestOutputBody,
} from "../_internal/api/types.gen.js";
import type { ResourceClient } from "./_client.js";

export class ObservationsResource {
  constructor(private readonly client: ResourceClient) {}

  /** Store an idempotent metadata-only batch; projection occurs independently. `POST /workspaces/{workspaceId}/observations` */
  async accept(
    workspaceId: string,
    body: WorkspaceIngestInputBody,
  ): Promise<WorkspaceIngestOutputBody | null> {
    return this.client.invoke(observationsAccept, { path: { workspaceId }, body });
  }

  /** Check storage and projection separately. `GET /workspaces/{workspaceId}/observations/{sourceEventId}` */
  async receipt(
    workspaceId: string,
    sourceEventId: string,
    query: ObservationsReceiptData["query"] = {},
  ): Promise<ActivityReceipt | null> {
    return this.client.invoke(observationsReceipt, { path: { workspaceId, sourceEventId }, query });
  }
}
