// Generated by tools/generate-operations.py. Regenerate from the server contract.
import { templatesList, templatesPublish } from "../_internal/api/sdk.gen.js";
import type {
  ActivityTemplate,
  WorkspaceStatusOutputBody,
  WorkspaceTemplateListOutputBody,
} from "../_internal/api/types.gen.js";
import type { ResourceClient } from "./_client.js";

export class TemplatesResource {
  constructor(private readonly client: ResourceClient) {}

  /** Discover public and organization-private immutable business templates. `GET /templates` */
  async list(): Promise<WorkspaceTemplateListOutputBody | null> {
    return this.client.invoke(templatesList, {});
  }

  /** Publish immutable configuration only; never production data. `POST /templates` */
  async publish(body: ActivityTemplate): Promise<WorkspaceStatusOutputBody | null> {
    return this.client.invoke(templatesPublish, { body });
  }
}
