// Generated by tools/generate-operations.py. Regenerate from the server contract.
import {
  workspacesActivate,
  workspacesCreate,
  workspacesGet,
  workspacesList,
  workspacesPreview,
  workspacesRevisions,
  workspacesSaveRevision,
  workspacesSchema,
  workspacesValidate,
} from "../_internal/api/sdk.gen.js";
import type {
  ActivateInputBody,
  ActivityRevision,
  ActivityWorkspace,
  ActivityWorkspaceSpec,
  CreateInputBody,
  RevisionListOutputBody,
  WorkspaceEntitiesOutputBody,
  WorkspaceListOutputBody,
  WorkspacePreviewInputBody,
  WorkspaceStatusOutputBody,
} from "../_internal/api/types.gen.js";
import type { ResourceClient } from "./_client.js";

export class WorkspacesResource {
  constructor(private readonly client: ResourceClient) {}

  /** List organization workspaces. `GET /workspaces` */
  async list(): Promise<WorkspaceListOutputBody | null> {
    return this.client.invoke(workspacesList, {});
  }

  /** Create an organization-owned workspace from a spec. `POST /workspaces` */
  async create(body: CreateInputBody): Promise<ActivityWorkspace | null> {
    return this.client.invoke(workspacesCreate, { body });
  }

  /** Preview a spec against synthetic metadata-only observations. `POST /workspaces/preview` */
  async preview(body: WorkspacePreviewInputBody): Promise<WorkspaceEntitiesOutputBody | null> {
    return this.client.invoke(workspacesPreview, { body });
  }

  /** Read the versioned declarative workspace JSON Schema. `GET /workspaces/schema` */
  async schema(): Promise<unknown | null> {
    return this.client.invoke(workspacesSchema, {});
  }

  /** Validate a workspace spec without saving or executing it. `POST /workspaces/validate` */
  async validate(body: ActivityWorkspaceSpec): Promise<WorkspaceStatusOutputBody | null> {
    return this.client.invoke(workspacesValidate, { body });
  }

  /** Read workspace activation and rebuild state. `GET /workspaces/{workspaceId}` */
  async get(workspaceId: string): Promise<ActivityWorkspace | null> {
    return this.client.invoke(workspacesGet, { path: { workspaceId } });
  }

  /** Build a revision before activation; use a previous revision for rollback. `POST /workspaces/{workspaceId}/activate` */
  async activate(
    workspaceId: string,
    body: ActivateInputBody,
  ): Promise<WorkspaceStatusOutputBody | null> {
    return this.client.invoke(workspacesActivate, { path: { workspaceId }, body });
  }

  /** List immutable spec revisions for diff, upgrade or rollback. `GET /workspaces/{workspaceId}/revisions` */
  async revisions(workspaceId: string): Promise<RevisionListOutputBody | null> {
    return this.client.invoke(workspacesRevisions, { path: { workspaceId } });
  }

  /** Save a validated immutable draft revision. `POST /workspaces/{workspaceId}/revisions` */
  async saveRevision(
    workspaceId: string,
    body: ActivityWorkspaceSpec,
  ): Promise<ActivityRevision | null> {
    return this.client.invoke(workspacesSaveRevision, { path: { workspaceId }, body });
  }
}
