// Generated by tools/generate-operations.py. Regenerate from the server contract.
import {
  workspacesActivate,
  workspacesActivateDraft,
  workspacesApplyDraftOps,
  workspacesCatalog,
  workspacesConnect,
  workspacesCreate,
  workspacesCreateAccessGrant,
  workspacesDeleteAccessGrant,
  workspacesDescribe,
  workspacesDiscardDraft,
  workspacesDraft,
  workspacesDraftChanges,
  workspacesGet,
  workspacesList,
  workspacesListAccessGrants,
  workspacesPreview,
  workspacesReplaceDraft,
  workspacesRevisions,
  workspacesSaveRevision,
  workspacesSchema,
  workspacesUpdateAccessGrant,
  workspacesValidate,
} from "../_internal/api/sdk.gen.js";
import type {
  ActivateDraftInputBody,
  ActivateDraftOutputBody,
  ActivateInputBody,
  ActivityCatalog,
  ActivityConnectResult,
  ActivityDescription,
  ActivityDraftView,
  ActivityGrant,
  ActivityRevision,
  ActivityWorkspace,
  ActivityWorkspaceSpec,
  ChangesOutputBody,
  ConnectInputBody,
  CreateInputBody,
  GrantInputBody,
  GrantListOutputBody,
  GrantUpdateInputBody,
  OpsInputBody,
  ReplaceInputBody,
  RevisionListOutputBody,
  ValidateOutputBody,
  WorkspaceEntitiesOutputBody,
  WorkspaceListOutputBody,
  WorkspacePreviewInputBody,
  WorkspaceStatusOutputBody,
  WorkspacesCatalogData,
} from "../_internal/api/types.gen.js";
import type { ResourceClient } from "./_client.js";

export class WorkspacesResource {
  constructor(private readonly client: ResourceClient) {}

  /** List organization workspaces. `GET /workspaces` */
  async list(): Promise<WorkspaceListOutputBody | null> {
    return this.client.invoke(workspacesList, {});
  }

  /** Create a workspace for an application, from a full or blank spec. `POST /workspaces` */
  async create(body: CreateInputBody): Promise<ActivityWorkspace | null> {
    return this.client.invoke(workspacesCreate, { body });
  }

  /** Preview the entities a spec projects from sample observations; nothing is stored. `POST /workspaces/preview` */
  async preview(body: WorkspacePreviewInputBody): Promise<WorkspaceEntitiesOutputBody | null> {
    return this.client.invoke(workspacesPreview, { body });
  }

  /** Read the workspace spec JSON Schema. `GET /workspaces/schema` */
  async schema(): Promise<unknown | null> {
    return this.client.invoke(workspacesSchema, {});
  }

  /** Validate a workspace spec without saving it; returns every issue. `POST /workspaces/validate` */
  async validate(body: ActivityWorkspaceSpec): Promise<ValidateOutputBody | null> {
    return this.client.invoke(workspacesValidate, { body });
  }

  /** Read workspace activation and rebuild state. `GET /workspaces/{workspaceId}` */
  async get(workspaceId: string): Promise<ActivityWorkspace | null> {
    return this.client.invoke(workspacesGet, { path: { workspaceId } });
  }

  /** List scoped data-access grants for members and API keys. `GET /workspaces/{workspaceId}/access-grants` */
  async listAccessGrants(workspaceId: string): Promise<GrantListOutputBody | null> {
    return this.client.invoke(workspacesListAccessGrants, { path: { workspaceId } });
  }

  /** Grant a member or API key access to records with the given scoping values (replaces that principal's values for the key). `POST /workspaces/{workspaceId}/access-grants` */
  async createAccessGrant(
    workspaceId: string,
    body: GrantInputBody,
  ): Promise<ActivityGrant | null> {
    return this.client.invoke(workspacesCreateAccessGrant, { path: { workspaceId }, body });
  }

  /** Remove a grant; a principal left with no grants in the organization is unscoped again. `DELETE /workspaces/{workspaceId}/access-grants/{grantId}` */
  async deleteAccessGrant(
    workspaceId: string,
    grantId: string,
  ): Promise<WorkspaceStatusOutputBody | null> {
    return this.client.invoke(workspacesDeleteAccessGrant, { path: { workspaceId, grantId } });
  }

  /** Replace a grant's allowed values. `PATCH /workspaces/{workspaceId}/access-grants/{grantId}` */
  async updateAccessGrant(
    workspaceId: string,
    grantId: string,
    body: GrantUpdateInputBody,
  ): Promise<ActivityGrant | null> {
    return this.client.invoke(workspacesUpdateAccessGrant, {
      path: { workspaceId, grantId },
      body,
    });
  }

  /** Build a revision before activation; use a previous revision for rollback. `POST /workspaces/{workspaceId}/activate` */
  async activate(
    workspaceId: string,
    body: ActivateInputBody,
  ): Promise<WorkspaceStatusOutputBody | null> {
    return this.client.invoke(workspacesActivate, { path: { workspaceId }, body });
  }

  /** Events actually received: counts, refs and attribute keys seen (declared and undeclared) and which entities consume each event. `GET /workspaces/{workspaceId}/catalog` */
  async catalog(
    workspaceId: string,
    query: WorkspacesCatalogData["query"] = {},
  ): Promise<ActivityCatalog | null> {
    return this.client.invoke(workspacesCatalog, { path: { workspaceId }, query });
  }

  /** Mint the application's publish key and return its env, OTLP, Sentry and SDK setup. `POST /workspaces/{workspaceId}/connect` */
  async connect(
    workspaceId: string,
    body: ConnectInputBody,
  ): Promise<ActivityConnectResult | null> {
    return this.client.invoke(workspacesConnect, { path: { workspaceId }, body });
  }

  /** Start here: explains this workspace in plain language plus the spec format, roles and draft ops an agent uses to change it. `GET /workspaces/{workspaceId}/describe` */
  async describe(workspaceId: string): Promise<ActivityDescription | null> {
    return this.client.invoke(workspacesDescribe, { path: { workspaceId } });
  }

  /** Discard the shared draft. `DELETE /workspaces/{workspaceId}/draft` */
  async discardDraft(workspaceId: string): Promise<WorkspaceStatusOutputBody | null> {
    return this.client.invoke(workspacesDiscardDraft, { path: { workspaceId } });
  }

  /** Read the shared draft of the workspace spec (created from the active spec on first read). `GET /workspaces/{workspaceId}/draft` */
  async draft(workspaceId: string): Promise<ActivityDraftView | null> {
    return this.client.invoke(workspacesDraft, { path: { workspaceId } });
  }

  /** Replace the whole draft spec (JSON editor); 409 with the current draft on a version mismatch. `PUT /workspaces/{workspaceId}/draft` */
  async replaceDraft(
    workspaceId: string,
    body: ReplaceInputBody,
  ): Promise<ActivityDraftView | null> {
    return this.client.invoke(workspacesReplaceDraft, { path: { workspaceId }, body });
  }

  /** Save the draft as a revision and rebuild projections with it; the draft is then cleared. `POST /workspaces/{workspaceId}/draft/activate` */
  async activateDraft(
    workspaceId: string,
    body?: ActivateDraftInputBody,
  ): Promise<ActivateDraftOutputBody | null> {
    return this.client.invoke(workspacesActivateDraft, { path: { workspaceId }, body });
  }

  /** List, in plain language, what the draft changes against the current spec. `GET /workspaces/{workspaceId}/draft/changes` */
  async draftChanges(workspaceId: string): Promise<ChangesOutputBody | null> {
    return this.client.invoke(workspacesDraftChanges, { path: { workspaceId } });
  }

  /** Apply typed edits to the shared draft atomically. `POST /workspaces/{workspaceId}/draft/ops` */
  async applyDraftOps(workspaceId: string, body: OpsInputBody): Promise<ActivityDraftView | null> {
    return this.client.invoke(workspacesApplyDraftOps, { path: { workspaceId }, body });
  }

  /** List immutable spec revisions for diff, upgrade or rollback. `GET /workspaces/{workspaceId}/revisions` */
  async revisions(workspaceId: string): Promise<RevisionListOutputBody | null> {
    return this.client.invoke(workspacesRevisions, { path: { workspaceId } });
  }

  /** Save a validated immutable revision. `POST /workspaces/{workspaceId}/revisions` */
  async saveRevision(
    workspaceId: string,
    body: ActivityWorkspaceSpec,
  ): Promise<ActivityRevision | null> {
    return this.client.invoke(workspacesSaveRevision, { path: { workspaceId }, body });
  }
}
