// Generated by tools/generate-operations.py. Do not edit manually.
#nullable enable

using System.Globalization;
using AxonPush.Internal;

namespace AxonPush.Operations;

public sealed class ActivityResource
{
    private readonly AxonPushTransport _transport;
    internal ActivityResource(AxonPushTransport transport) => _transport = transport;

    /// <summary>Read exact scoped business entities and concurrent operations.</summary>
    public Task<WorkspaceEntitiesOutputBody?> EntitiesAsync(string workspaceId, string? environment = null, string? entity = null, string? entityId = null, string? side = null, string? client = null, string? action = null, string? outcome = null, string? state = null, string? freshness = null, string? q = null, string? agentId = null, string? cursor = null, long? limit = null, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/activity";
        path = AddQuery(path, "environment", environment);
        path = AddQuery(path, "entity", entity);
        path = AddQuery(path, "entityId", entityId);
        path = AddQuery(path, "side", side);
        path = AddQuery(path, "client", client);
        path = AddQuery(path, "action", action);
        path = AddQuery(path, "outcome", outcome);
        path = AddQuery(path, "state", state);
        path = AddQuery(path, "freshness", freshness);
        path = AddQuery(path, "q", q);
        path = AddQuery(path, "agentId", agentId);
        path = AddQuery(path, "cursor", cursor);
        path = AddQuery(path, "limit", limit);
        return _transport.SendAsync<WorkspaceEntitiesOutputBody>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Delete agent evidence and install a replay tombstone.</summary>
    public Task<WorkspaceStatusOutputBody?> DeleteAgentAsync(string workspaceId, string agentId, string? environment = null, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/agents/{Uri.EscapeDataString(agentId)}";
        path = AddQuery(path, "environment", environment);
        return _transport.SendAsync<WorkspaceStatusOutputBody>(HttpMethod.Delete, path, null, cancellationToken);
    }

    /// <summary>Distinct lifecycle milestones and client activation; snapshots never count as joins.</summary>
    public Task<ActivityAnalytics?> AnalyticsAsync(string workspaceId, string? environment = null, string? entity = null, string? entityId = null, string? side = null, string? client = null, string? action = null, string? outcome = null, string? state = null, string? freshness = null, string? q = null, string? agentId = null, string? cursor = null, long? limit = null, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/analytics";
        path = AddQuery(path, "environment", environment);
        path = AddQuery(path, "entity", entity);
        path = AddQuery(path, "entityId", entityId);
        path = AddQuery(path, "side", side);
        path = AddQuery(path, "client", client);
        path = AddQuery(path, "action", action);
        path = AddQuery(path, "outcome", outcome);
        path = AddQuery(path, "state", state);
        path = AddQuery(path, "freshness", freshness);
        path = AddQuery(path, "q", q);
        path = AddQuery(path, "agentId", agentId);
        path = AddQuery(path, "cursor", cursor);
        path = AddQuery(path, "limit", limit);
        return _transport.SendAsync<ActivityAnalytics>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Read independent storage and projection freshness.</summary>
    public Task<object?> HealthAsync(string workspaceId, string? environment = null, string? entity = null, string? entityId = null, string? side = null, string? client = null, string? action = null, string? outcome = null, string? state = null, string? freshness = null, string? q = null, string? agentId = null, string? cursor = null, long? limit = null, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/health";
        path = AddQuery(path, "environment", environment);
        path = AddQuery(path, "entity", entity);
        path = AddQuery(path, "entityId", entityId);
        path = AddQuery(path, "side", side);
        path = AddQuery(path, "client", client);
        path = AddQuery(path, "action", action);
        path = AddQuery(path, "outcome", outcome);
        path = AddQuery(path, "state", state);
        path = AddQuery(path, "freshness", freshness);
        path = AddQuery(path, "q", q);
        path = AddQuery(path, "agentId", agentId);
        path = AddQuery(path, "cursor", cursor);
        path = AddQuery(path, "limit", limit);
        return _transport.SendAsync<object>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Read lifecycle incidents and recovery without duplicate notifications.</summary>
    public Task<WorkspaceIncidentsOutputBody?> IncidentsAsync(string workspaceId, string? environment = null, string? entity = null, string? entityId = null, string? side = null, string? client = null, string? action = null, string? outcome = null, string? state = null, string? freshness = null, string? q = null, string? agentId = null, string? cursor = null, long? limit = null, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/incidents";
        path = AddQuery(path, "environment", environment);
        path = AddQuery(path, "entity", entity);
        path = AddQuery(path, "entityId", entityId);
        path = AddQuery(path, "side", side);
        path = AddQuery(path, "client", client);
        path = AddQuery(path, "action", action);
        path = AddQuery(path, "outcome", outcome);
        path = AddQuery(path, "state", state);
        path = AddQuery(path, "freshness", freshness);
        path = AddQuery(path, "q", q);
        path = AddQuery(path, "agentId", agentId);
        path = AddQuery(path, "cursor", cursor);
        path = AddQuery(path, "limit", limit);
        return _transport.SendAsync<WorkspaceIncidentsOutputBody>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Exact distinct entity counts with a visible 15 minute activity window.</summary>
    public Task<object?> SummaryAsync(string workspaceId, string? environment = null, string? entity = null, string? entityId = null, string? side = null, string? client = null, string? action = null, string? outcome = null, string? state = null, string? freshness = null, string? q = null, string? agentId = null, string? cursor = null, long? limit = null, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/summary";
        path = AddQuery(path, "environment", environment);
        path = AddQuery(path, "entity", entity);
        path = AddQuery(path, "entityId", entityId);
        path = AddQuery(path, "side", side);
        path = AddQuery(path, "client", client);
        path = AddQuery(path, "action", action);
        path = AddQuery(path, "outcome", outcome);
        path = AddQuery(path, "state", state);
        path = AddQuery(path, "freshness", freshness);
        path = AddQuery(path, "q", q);
        path = AddQuery(path, "agentId", agentId);
        path = AddQuery(path, "cursor", cursor);
        path = AddQuery(path, "limit", limit);
        return _transport.SendAsync<object>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Follow chronological source evidence across traces.</summary>
    public Task<WorkspaceTimelineOutputBody?> TimelineAsync(string workspaceId, string? environment = null, string? entity = null, string? entityId = null, string? side = null, string? client = null, string? action = null, string? outcome = null, string? state = null, string? freshness = null, string? q = null, string? agentId = null, string? cursor = null, long? limit = null, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/timeline";
        path = AddQuery(path, "environment", environment);
        path = AddQuery(path, "entity", entity);
        path = AddQuery(path, "entityId", entityId);
        path = AddQuery(path, "side", side);
        path = AddQuery(path, "client", client);
        path = AddQuery(path, "action", action);
        path = AddQuery(path, "outcome", outcome);
        path = AddQuery(path, "state", state);
        path = AddQuery(path, "freshness", freshness);
        path = AddQuery(path, "q", q);
        path = AddQuery(path, "agentId", agentId);
        path = AddQuery(path, "cursor", cursor);
        path = AddQuery(path, "limit", limit);
        return _transport.SendAsync<WorkspaceTimelineOutputBody>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Aggregate configured business widgets over the active entity revision.</summary>
    public Task<WorkspaceWidgetsOutputBody?> WidgetsAsync(string workspaceId, string? environment = null, string? entity = null, string? entityId = null, string? side = null, string? client = null, string? action = null, string? outcome = null, string? state = null, string? freshness = null, string? q = null, string? agentId = null, string? cursor = null, long? limit = null, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/widgets";
        path = AddQuery(path, "environment", environment);
        path = AddQuery(path, "entity", entity);
        path = AddQuery(path, "entityId", entityId);
        path = AddQuery(path, "side", side);
        path = AddQuery(path, "client", client);
        path = AddQuery(path, "action", action);
        path = AddQuery(path, "outcome", outcome);
        path = AddQuery(path, "state", state);
        path = AddQuery(path, "freshness", freshness);
        path = AddQuery(path, "q", q);
        path = AddQuery(path, "agentId", agentId);
        path = AddQuery(path, "cursor", cursor);
        path = AddQuery(path, "limit", limit);
        return _transport.SendAsync<WorkspaceWidgetsOutputBody>(HttpMethod.Get, path, null, cancellationToken);
    }

    private static string AddQuery(string path, string key, object? value)
    {
        if (value is null) return path;
        var text = Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty;
        return path + (path.Contains('?') ? "&" : "?") + Uri.EscapeDataString(key) + "=" + Uri.EscapeDataString(text);
    }
}
