// Generated by tools/generate-operations.py. Do not edit manually.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace AxonPush.Operations;

public sealed record ActivateInputBody
{
    [JsonPropertyName("generation")]
    public long Generation { get; init; }
    [JsonPropertyName("revision")]
    public string Revision { get; init; } = default!;
}

public sealed record ActivityActivity
{
    [JsonPropertyName("action")]
    public string? Action { get; init; }
    [JsonPropertyName("attempts")]
    public long? Attempts { get; init; }
    [JsonPropertyName("duration_ms")]
    public double? DurationMs { get; init; }
    [JsonPropertyName("error_category")]
    public string? ErrorCategory { get; init; }
    [JsonPropertyName("evidence")]
    public string Evidence { get; init; } = default!;
    [JsonPropertyName("expected_seconds")]
    public long? ExpectedSeconds { get; init; }
    [JsonPropertyName("family")]
    public string Family { get; init; } = default!;
    [JsonPropertyName("input_tokens")]
    public long? InputTokens { get; init; }
    [JsonPropertyName("join_method")]
    public string? JoinMethod { get; init; }
    [JsonPropertyName("model")]
    public string? Model { get; init; }
    [JsonPropertyName("next_actor")]
    public string? NextActor { get; init; }
    [JsonPropertyName("outcome")]
    public string Outcome { get; init; } = default!;
    [JsonPropertyName("output_tokens")]
    public long? OutputTokens { get; init; }
    [JsonPropertyName("registration_source")]
    public string? RegistrationSource { get; init; }
    [JsonPropertyName("snapshot")]
    public bool? Snapshot { get; init; }
    [JsonPropertyName("state")]
    public string? State { get; init; }
    [JsonPropertyName("transport")]
    public string? Transport { get; init; }
}

public sealed record ActivityActor
{
    [JsonPropertyName("agent_id")]
    public string? AgentId { get; init; }
    [JsonPropertyName("initiating_agent_id")]
    public string? InitiatingAgentId { get; init; }
    [JsonPropertyName("participant_side")]
    public string? ParticipantSide { get; init; }
    [JsonPropertyName("related_agent_ids")]
    public IReadOnlyList<string>? RelatedAgentIds { get; init; }
    [JsonPropertyName("type")]
    public string Type { get; init; } = default!;
}

public sealed record ActivityAlert
{
    [JsonPropertyName("afterSeconds")]
    public long AfterSeconds { get; init; }
    [JsonPropertyName("entity")]
    public string Entity { get; init; } = default!;
    [JsonPropertyName("name")]
    public string Name { get; init; } = default!;
    [JsonPropertyName("state")]
    public string State { get; init; } = default!;
}

public sealed record ActivityAnalytics
{
    [JsonPropertyName("activations")]
    public IReadOnlyList<ActivityCohortCount>? Activations { get; init; } = default!;
    [JsonPropertyName("asOf")]
    public DateTimeOffset AsOf { get; init; }
    [JsonPropertyName("attempts")]
    public IReadOnlyList<ActivityCohortCount>? Attempts { get; init; } = default!;
    [JsonPropertyName("clients")]
    public IReadOnlyList<ActivityBreakdown>? Clients { get; init; } = default!;
    [JsonPropertyName("funnels")]
    public IReadOnlyList<ActivityFunnelResult>? Funnels { get; init; } = default!;
    [JsonPropertyName("windowDays")]
    public long WindowDays { get; init; }
}

public sealed record ActivityBreakdown
{
    [JsonPropertyName("active15m")]
    public long Active15m { get; init; }
    [JsonPropertyName("agents")]
    public long Agents { get; init; }
    [JsonPropertyName("client")]
    public string Client { get; init; } = default!;
    [JsonPropertyName("side")]
    public string Side { get; init; } = default!;
}

public sealed record ActivityClient
{
    [JsonPropertyName("attribution_source")]
    public string? AttributionSource { get; init; }
    [JsonPropertyName("confidence")]
    public string Confidence { get; init; } = default!;
    [JsonPropertyName("conflict")]
    public bool? Conflict { get; init; }
    [JsonPropertyName("evidence")]
    public IReadOnlyList<ActivityClientEvidence>? Evidence { get; init; }
    [JsonPropertyName("family")]
    public string Family { get; init; } = default!;
    [JsonPropertyName("reported_name")]
    public string? ReportedName { get; init; }
    [JsonPropertyName("version")]
    public string? Version { get; init; }
}

public sealed record ActivityClientEvidence
{
    [JsonPropertyName("confidence")]
    public string Confidence { get; init; } = default!;
    [JsonPropertyName("family")]
    public string Family { get; init; } = default!;
    [JsonPropertyName("name")]
    public string? Name { get; init; }
    [JsonPropertyName("source")]
    public string Source { get; init; } = default!;
    [JsonPropertyName("version")]
    public string? Version { get; init; }
}

public sealed record ActivityCohortCount
{
    [JsonPropertyName("client")]
    public string Client { get; init; } = default!;
    [JsonPropertyName("count")]
    public long Count { get; init; }
    [JsonPropertyName("side")]
    public string Side { get; init; } = default!;
}

public sealed record ActivityCorrelation
{
    [JsonPropertyName("application_id")]
    public string? ApplicationId { get; init; }
    [JsonPropertyName("causation_id")]
    public string? CausationId { get; init; }
    [JsonPropertyName("connection_ref")]
    public string? ConnectionRef { get; init; }
    [JsonPropertyName("job_id")]
    public string? JobId { get; init; }
    [JsonPropertyName("join_attempt_id")]
    public string? JoinAttemptId { get; init; }
    [JsonPropertyName("operation_id")]
    public string? OperationId { get; init; }
    [JsonPropertyName("request_id")]
    public string? RequestId { get; init; }
    [JsonPropertyName("role_id")]
    public string? RoleId { get; init; }
    [JsonPropertyName("span_id")]
    public string? SpanId { get; init; }
    [JsonPropertyName("thread_id")]
    public string? ThreadId { get; init; }
    [JsonPropertyName("trace_id")]
    public string? TraceId { get; init; }
}

public sealed record ActivityEntity
{
    [JsonPropertyName("evidence")]
    public string Evidence { get; init; } = default!;
    [JsonPropertyName("fields")]
    public IReadOnlyDictionary<string, JsonElement> Fields { get; init; } = default!;
    [JsonPropertyName("id")]
    public string Id { get; init; } = default!;
    [JsonPropertyName("lastActivityAt")]
    public DateTimeOffset? LastActivityAt { get; init; }
    [JsonPropertyName("occurredAt")]
    public DateTimeOffset OccurredAt { get; init; }
    [JsonPropertyName("receivedAt")]
    public DateTimeOffset ReceivedAt { get; init; }
    [JsonPropertyName("snapshot")]
    public bool Snapshot { get; init; }
    [JsonPropertyName("type")]
    public string Type { get; init; } = default!;
    [JsonPropertyName("versions")]
    public IReadOnlyDictionary<string, ActivityFieldVersion> Versions { get; init; } = default!;
}

public sealed record ActivityEntityDefinition
{
    [JsonPropertyName("fields")]
    public IReadOnlyList<string>? Fields { get; init; } = default!;
    [JsonPropertyName("label")]
    public string Label { get; init; } = default!;
    [JsonPropertyName("terminalStates")]
    public IReadOnlyList<string>? TerminalStates { get; init; }
    [JsonPropertyName("type")]
    public string Type { get; init; } = default!;
}

public sealed record ActivityFieldVersion
{
    [JsonPropertyName("eventId")]
    public string EventId { get; init; } = default!;
    [JsonPropertyName("revision")]
    public long Revision { get; init; }
    [JsonPropertyName("sourceRef")]
    public string SourceRef { get; init; } = default!;
    [JsonPropertyName("time")]
    public DateTimeOffset Time { get; init; }
}

public sealed record ActivityFunnel
{
    [JsonPropertyName("entity")]
    public string Entity { get; init; } = default!;
    [JsonPropertyName("name")]
    public string Name { get; init; } = default!;
    [JsonPropertyName("stages")]
    public IReadOnlyList<string>? Stages { get; init; } = default!;
}

public sealed record ActivityFunnelResult
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = default!;
    [JsonPropertyName("stages")]
    public IReadOnlyList<ActivityStageCount>? Stages { get; init; } = default!;
}

public sealed record ActivityIncident
{
    [JsonPropertyName("affected")]
    public long Affected { get; init; }
    [JsonPropertyName("checkedAt")]
    public DateTimeOffset CheckedAt { get; init; }
    [JsonPropertyName("entity")]
    public string Entity { get; init; } = default!;
    [JsonPropertyName("id")]
    public string Id { get; init; } = default!;
    [JsonPropertyName("name")]
    public string Name { get; init; } = default!;
    [JsonPropertyName("openedAt")]
    public DateTimeOffset OpenedAt { get; init; }
    [JsonPropertyName("resolvedAt")]
    public DateTimeOffset? ResolvedAt { get; init; }
}

public sealed record ActivityMapping
{
    [JsonPropertyName("entity")]
    public string Entity { get; init; } = default!;
    [JsonPropertyName("event")]
    public string Event { get; init; } = default!;
    [JsonPropertyName("fields")]
    public IReadOnlyDictionary<string, string>? Fields { get; init; }
    [JsonPropertyName("idPath")]
    public string IdPath { get; init; } = default!;
    [JsonPropertyName("values")]
    public IReadOnlyDictionary<string, string>? Values { get; init; }
}

public sealed record ActivityObservation
{
    [JsonPropertyName("activity")]
    public ActivityActivity Activity { get; init; } = default!;
    [JsonPropertyName("actor")]
    public ActivityActor Actor { get; init; } = default!;
    [JsonPropertyName("client")]
    public ActivityClient Client { get; init; } = default!;
    [JsonPropertyName("correlation")]
    public ActivityCorrelation Correlation { get; init; } = default!;
    [JsonPropertyName("event_name")]
    public string EventName { get; init; } = default!;
    [JsonPropertyName("occurred_at")]
    public DateTimeOffset OccurredAt { get; init; }
    [JsonPropertyName("pipeline")]
    public ActivityPipelineHealth? Pipeline { get; init; }
    [JsonPropertyName("release")]
    public string? Release { get; init; }
    [JsonPropertyName("schema_version")]
    public long SchemaVersion { get; init; }
    [JsonPropertyName("service")]
    public string Service { get; init; } = default!;
    [JsonPropertyName("source")]
    public ActivitySource Source { get; init; } = default!;
    [JsonPropertyName("source_event_id")]
    public string SourceEventId { get; init; } = default!;
}

public sealed record ActivityPipelineHealth
{
    [JsonPropertyName("capture_failures")]
    public long CaptureFailures { get; init; }
    [JsonPropertyName("dead_letters")]
    public long DeadLetters { get; init; }
    [JsonPropertyName("dropped_transient")]
    public long DroppedTransient { get; init; }
    [JsonPropertyName("last_export_at")]
    public DateTimeOffset? LastExportAt { get; init; }
    [JsonPropertyName("pending")]
    public long Pending { get; init; }
    [JsonPropertyName("reconciled_at")]
    public DateTimeOffset? ReconciledAt { get; init; }
    [JsonPropertyName("reconciled_records")]
    public long ReconciledRecords { get; init; }
    [JsonPropertyName("retries")]
    public long Retries { get; init; }
}

public sealed record ActivityReceipt
{
    [JsonPropertyName("projectedAt")]
    public DateTimeOffset? ProjectedAt { get; init; }
    [JsonPropertyName("receivedAt")]
    public DateTimeOffset ReceivedAt { get; init; }
    [JsonPropertyName("sourceEventId")]
    public string SourceEventId { get; init; } = default!;
    [JsonPropertyName("status")]
    public string Status { get; init; } = default!;
}

public sealed record ActivityRecord
{
    [JsonPropertyName("observation")]
    public ActivityObservation Observation { get; init; } = default!;
    [JsonPropertyName("projectedAt")]
    public DateTimeOffset? ProjectedAt { get; init; }
    [JsonPropertyName("receivedAt")]
    public DateTimeOffset ReceivedAt { get; init; }
}

public sealed record ActivityRevision
{
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; init; } = default!;
    [JsonPropertyName("id")]
    public string Id { get; init; } = default!;
    [JsonPropertyName("spec")]
    public ActivityWorkspaceSpec Spec { get; init; } = default!;
}

public sealed record ActivitySource
{
    [JsonPropertyName("record_id")]
    public string? RecordId { get; init; }
    [JsonPropertyName("record_type")]
    public string? RecordType { get; init; }
    [JsonPropertyName("revision")]
    public long? Revision { get; init; }
}

public sealed record ActivityStageCount
{
    [JsonPropertyName("count")]
    public long Count { get; init; }
    [JsonPropertyName("stage")]
    public string Stage { get; init; } = default!;
}

public sealed record ActivityTemplate
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = default!;
    [JsonPropertyName("spec")]
    public ActivityWorkspaceSpec Spec { get; init; } = default!;
    [JsonPropertyName("version")]
    public long Version { get; init; }
    [JsonPropertyName("visibility")]
    public string Visibility { get; init; } = default!;
}

public sealed record ActivityTemplateRef
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = default!;
    [JsonPropertyName("version")]
    public long Version { get; init; }
}

public sealed record ActivityWidget
{
    [JsonPropertyName("entity")]
    public string? Entity { get; init; }
    [JsonPropertyName("field")]
    public string? Field { get; init; }
    [JsonPropertyName("title")]
    public string Title { get; init; } = default!;
    [JsonPropertyName("type")]
    public string Type { get; init; } = default!;
}

public sealed record ActivityWidgetPoint
{
    [JsonPropertyName("count")]
    public long Count { get; init; }
    [JsonPropertyName("label")]
    public string Label { get; init; } = default!;
    [JsonPropertyName("value")]
    public double? Value { get; init; }
}

public sealed record ActivityWidgetSeries
{
    [JsonPropertyName("entity")]
    public string Entity { get; init; } = default!;
    [JsonPropertyName("field")]
    public string Field { get; init; } = default!;
    [JsonPropertyName("points")]
    public IReadOnlyList<ActivityWidgetPoint>? Points { get; init; } = default!;
    [JsonPropertyName("title")]
    public string Title { get; init; } = default!;
    [JsonPropertyName("type")]
    public string Type { get; init; } = default!;
}

public sealed record ActivityWorkspace
{
    [JsonPropertyName("activeRevision")]
    public string? ActiveRevision { get; init; } = default!;
    [JsonPropertyName("appId")]
    public string AppId { get; init; } = default!;
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }
    [JsonPropertyName("generation")]
    public long Generation { get; init; }
    [JsonPropertyName("id")]
    public string Id { get; init; } = default!;
    [JsonPropertyName("name")]
    public string Name { get; init; } = default!;
    [JsonPropertyName("requestedRevision")]
    public string? RequestedRevision { get; init; } = default!;
}

public sealed record ActivityWorkspaceSpec
{
    [JsonPropertyName("alerts")]
    public IReadOnlyList<ActivityAlert>? Alerts { get; init; }
    [JsonPropertyName("description")]
    public string? Description { get; init; }
    [JsonPropertyName("entities")]
    public IReadOnlyList<ActivityEntityDefinition>? Entities { get; init; } = default!;
    [JsonPropertyName("funnels")]
    public IReadOnlyList<ActivityFunnel>? Funnels { get; init; }
    [JsonPropertyName("mappings")]
    public IReadOnlyList<ActivityMapping>? Mappings { get; init; } = default!;
    [JsonPropertyName("name")]
    public string Name { get; init; } = default!;
    [JsonPropertyName("schemaVersion")]
    public long SchemaVersion { get; init; }
    [JsonPropertyName("template")]
    public ActivityTemplateRef? Template { get; init; }
    [JsonPropertyName("widgets")]
    public IReadOnlyList<ActivityWidget>? Widgets { get; init; } = default!;
}

public sealed record CreateInputBody
{
    [JsonPropertyName("appId")]
    public string AppId { get; init; } = default!;
    [JsonPropertyName("spec")]
    public ActivityWorkspaceSpec Spec { get; init; } = default!;
}

public sealed record RevisionListOutputBody
{
    [JsonPropertyName("revisions")]
    public IReadOnlyList<ActivityRevision>? Revisions { get; init; } = default!;
}

public sealed record WorkspaceEntitiesOutputBody
{
    [JsonPropertyName("entities")]
    public IReadOnlyList<ActivityEntity>? Entities { get; init; } = default!;
    [JsonPropertyName("nextCursor")]
    public string? NextCursor { get; init; }
}

public sealed record WorkspaceIncidentsOutputBody
{
    [JsonPropertyName("incidents")]
    public IReadOnlyList<ActivityIncident>? Incidents { get; init; } = default!;
}

public sealed record WorkspaceIngestInputBody
{
    [JsonPropertyName("environment")]
    public string Environment { get; init; } = default!;
    [JsonPropertyName("observations")]
    public IReadOnlyList<ActivityObservation>? Observations { get; init; } = default!;
}

public sealed record WorkspaceIngestOutputBody
{
    [JsonPropertyName("receipts")]
    public IReadOnlyList<ActivityReceipt>? Receipts { get; init; } = default!;
}

public sealed record WorkspaceListOutputBody
{
    [JsonPropertyName("workspaces")]
    public IReadOnlyList<ActivityWorkspace>? Workspaces { get; init; } = default!;
}

public sealed record WorkspacePreviewInputBody
{
    [JsonPropertyName("observations")]
    public IReadOnlyList<ActivityObservation>? Observations { get; init; } = default!;
    [JsonPropertyName("spec")]
    public ActivityWorkspaceSpec Spec { get; init; } = default!;
}

public sealed record WorkspaceStatusOutputBody
{
    [JsonPropertyName("status")]
    public string Status { get; init; } = default!;
}

public sealed record WorkspaceTemplateListOutputBody
{
    [JsonPropertyName("templates")]
    public IReadOnlyList<ActivityTemplate>? Templates { get; init; } = default!;
}

public sealed record WorkspaceTimelineOutputBody
{
    [JsonPropertyName("events")]
    public IReadOnlyList<ActivityRecord>? Events { get; init; } = default!;
}

public sealed record WorkspaceWidgetsOutputBody
{
    [JsonPropertyName("series")]
    public IReadOnlyList<ActivityWidgetSeries>? Series { get; init; } = default!;
}
