// Generated by tools/generate-operations.py. Do not edit manually.
#nullable enable

using System.Globalization;
using AxonPush.Internal;

namespace AxonPush.Operations;

public sealed class ObservationsResource
{
    private readonly AxonPushTransport _transport;
    internal ObservationsResource(AxonPushTransport transport) => _transport = transport;

    /// <summary>Store an idempotent metadata-only batch; undeclared attributes are dropped and counted.</summary>
    public Task<ActivityIngestReport?> AcceptAsync(string workspaceId, WorkspaceIngestInputBody body, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/observations";
        return _transport.SendObservationAsync<ActivityIngestReport>(HttpMethod.Post, path, body, cancellationToken);
    }

    /// <summary>Check storage and projection separately.</summary>
    public Task<ActivityReceipt?> ReceiptAsync(string workspaceId, string sourceEventId, string? environment = null, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/observations/{Uri.EscapeDataString(sourceEventId)}";
        path = AddQuery(path, "environment", environment);
        return _transport.SendAsync<ActivityReceipt>(HttpMethod.Get, path, null, cancellationToken);
    }

    private static string AddQuery(string path, string key, object? value)
    {
        if (value is null) return path;
        var text = Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty;
        return path + (path.Contains('?') ? "&" : "?") + Uri.EscapeDataString(key) + "=" + Uri.EscapeDataString(text);
    }
}
