// Generated by tools/generate-operations.py. Do not edit manually.
#nullable enable

using System.Globalization;
using AxonPush.Internal;

namespace AxonPush.Operations;

public sealed class TemplatesResource
{
    private readonly AxonPushTransport _transport;
    internal TemplatesResource(AxonPushTransport transport) => _transport = transport;

    /// <summary>Discover public and organization-private immutable workspace templates.</summary>
    public Task<WorkspaceTemplateListOutputBody?> ListAsync(CancellationToken cancellationToken = default)
    {
        var path = $"templates";
        return _transport.SendAsync<WorkspaceTemplateListOutputBody>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Publish immutable configuration only; never production data.</summary>
    public Task<WorkspaceStatusOutputBody?> PublishAsync(ActivityTemplate body, CancellationToken cancellationToken = default)
    {
        var path = $"templates";
        return _transport.SendAsync<WorkspaceStatusOutputBody>(HttpMethod.Post, path, body, cancellationToken);
    }

    private static string AddQuery(string path, string key, object? value)
    {
        if (value is null) return path;
        var text = Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty;
        return path + (path.Contains('?') ? "&" : "?") + Uri.EscapeDataString(key) + "=" + Uri.EscapeDataString(text);
    }
}
