// Generated by tools/generate-operations.py. Do not edit manually.
#nullable enable

using System.Globalization;
using AxonPush.Internal;

namespace AxonPush.Operations;

public sealed class WorkspacesResource
{
    private readonly AxonPushTransport _transport;
    internal WorkspacesResource(AxonPushTransport transport) => _transport = transport;

    /// <summary>List organization workspaces.</summary>
    public Task<WorkspaceListOutputBody?> ListAsync(CancellationToken cancellationToken = default)
    {
        var path = $"workspaces";
        return _transport.SendAsync<WorkspaceListOutputBody>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Create an organization-owned workspace from a spec.</summary>
    public Task<ActivityWorkspace?> CreateAsync(CreateInputBody body, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces";
        return _transport.SendAsync<ActivityWorkspace>(HttpMethod.Post, path, body, cancellationToken);
    }

    /// <summary>Preview a spec against synthetic metadata-only observations.</summary>
    public Task<WorkspaceEntitiesOutputBody?> PreviewAsync(WorkspacePreviewInputBody body, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/preview";
        return _transport.SendAsync<WorkspaceEntitiesOutputBody>(HttpMethod.Post, path, body, cancellationToken);
    }

    /// <summary>Read the versioned declarative workspace JSON Schema.</summary>
    public Task<object?> SchemaAsync(CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/schema";
        return _transport.SendAsync<object>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Validate a workspace spec without saving or executing it.</summary>
    public Task<WorkspaceStatusOutputBody?> ValidateAsync(ActivityWorkspaceSpec body, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/validate";
        return _transport.SendAsync<WorkspaceStatusOutputBody>(HttpMethod.Post, path, body, cancellationToken);
    }

    /// <summary>Read workspace activation and rebuild state.</summary>
    public Task<ActivityWorkspace?> GetAsync(string workspaceId, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}";
        return _transport.SendAsync<ActivityWorkspace>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Build a revision before activation; use a previous revision for rollback.</summary>
    public Task<WorkspaceStatusOutputBody?> ActivateAsync(string workspaceId, ActivateInputBody body, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/activate";
        return _transport.SendAsync<WorkspaceStatusOutputBody>(HttpMethod.Post, path, body, cancellationToken);
    }

    /// <summary>List immutable spec revisions for diff, upgrade or rollback.</summary>
    public Task<RevisionListOutputBody?> RevisionsAsync(string workspaceId, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/revisions";
        return _transport.SendAsync<RevisionListOutputBody>(HttpMethod.Get, path, null, cancellationToken);
    }

    /// <summary>Save a validated immutable draft revision.</summary>
    public Task<ActivityRevision?> SaveRevisionAsync(string workspaceId, ActivityWorkspaceSpec body, CancellationToken cancellationToken = default)
    {
        var path = $"workspaces/{Uri.EscapeDataString(workspaceId)}/revisions";
        return _transport.SendAsync<ActivityRevision>(HttpMethod.Post, path, body, cancellationToken);
    }

    private static string AddQuery(string path, string key, object? value)
    {
        if (value is null) return path;
        var text = Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty;
        return path + (path.Contains('?') ? "&" : "?") + Uri.EscapeDataString(key) + "=" + Uri.EscapeDataString(text);
    }
}
