// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AbuseFlagDto = {
    createdAt: string;
    flagId: string;
    orgId: string;
    reason: string;
    reviewedAt?: string;
    reviewedBy?: string;
    severity: string;
    signals?: unknown;
    status: string;
};

export type AccessRequestDto = {
    company: string;
    country?: string;
    createdAt: string;
    email: string;
    invitationCode?: string;
    name?: string;
    note?: string;
    orgId?: string;
    requestId: string;
    reviewedAt?: string;
    status: string;
    useCase: string;
};

export type AlertRuleDto = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    alertRuleId: string;
    appId?: string;
    createdAt: string;
    destination: string;
    destinationType: string;
    enabled: boolean;
    environmentId?: string;
    metric: string;
    model?: string;
    name: string;
    operator: string;
    orgId: string;
    release?: string;
    service?: string;
    threshold: number;
    updatedAt: string;
};

export type ApiKeyScope = {
    category: string;
    description: string;
    scope: string;
};

export type AppDto = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    appId: string;
    createdAt: string;
    creatorUserId?: string;
    name: string;
    orgId: string;
    updatedAt?: string;
};

export type AuditCapability = {
    enabled: boolean;
    formats: Array<string> | null;
};

export type BillingEventDto = {
    createdAt: string;
    error?: string;
    eventName: string;
    externalId: string;
    orgId: string;
    payload?: unknown;
    processedAt?: string;
};

export type BreakdownOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    dimension: string;
    rows: Array<BreakdownRowDto> | null;
};

export type BreakdownRowDto = {
    avgDurationMs?: number;
    costUsd: number;
    errorCount?: number;
    eventCount: number;
    key: string;
    totalTokens?: number;
};

export type BudgetCapability = {
    enabled: boolean;
    periods: Array<string> | null;
};

export type CapabilitiesOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    apiKeyScopes: Array<ApiKeyScope> | null;
    controls: Controls;
    featureFlags: FeatureFlags;
    license: LicenseStatus;
    version: string;
};

export type ChannelDto = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    appId: string;
    channelId: string;
    createdAt: string;
    name: string;
    orgId: string;
    updatedAt?: string;
};

export type CheckoutInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * monthly or annual
     */
    cadence?: string;
    /**
     * pro or team
     */
    plan: string;
};

export type Controls = {
    auditTrail: AuditCapability;
    costBudgets: BudgetCapability;
    inlineModeration: ModerationCapability;
};

export type CostBudget = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    appId?: string;
    budgetId: string;
    createdAt: string;
    dailyLimitUsd: number;
    enabled: boolean;
    monthlyLimitUsd: number;
    name: string;
    updatedAt: string;
};

export type CreateAppInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * App display name
     */
    name: string;
};

export type CreateChannelInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Channel name
     */
    name: string;
};

export type CreateEndpointInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    channelId: string;
    description?: string;
    /**
     * Event types to filter (empty = all)
     */
    eventTypes?: Array<string> | null;
    url: string;
};

export type CreateEndpointOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    active: boolean;
    channelId: string;
    createdAt: string;
    description?: string;
    endpointId: string;
    eventTypes: Array<string> | null;
    hasSecret: boolean;
    orgId?: string;
    /**
     * Signing secret, only returned at creation time
     */
    rawSecret: string;
    updatedAt?: string;
    url: string;
};

export type CreateEnvironmentInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    color?: string;
    isDefault?: boolean;
    isProduction?: boolean;
    /**
     * Environment display name
     */
    name: string;
    /**
     * URL-safe slug; derived from name when omitted
     */
    slug?: string;
};

export type CreateInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * scope to an app; empty means org-wide
     */
    appId?: string;
    /**
     * per-UTC-day ceiling in USD; 0 disables the daily cap
     */
    dailyLimitUsd?: number;
    /**
     * per-UTC-month ceiling in USD; 0 disables the monthly cap
     */
    monthlyLimitUsd?: number;
    name: string;
};

export type CreateInputBody1 = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    appId?: string;
    destination: string;
    destinationType: 'email' | 'webhook';
    enabled?: boolean;
    environmentId?: string;
    metric: 'error_count' | 'error_rate' | 'latency_ms' | 'cost_usd' | 'score';
    model?: string;
    /**
     * Alert rule display name
     */
    name: string;
    operator: 'gt' | 'gte' | 'lt' | 'lte';
    release?: string;
    service?: string;
    threshold: number;
};

export type CreateInputBody2 = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    endpointUrl: string;
    envSlug: string;
    eventTypeFilter?: Array<string> | null;
    /**
     * Header name -> value map. Stored server-side, never returned.
     */
    headers?: {
        [key: string]: string;
    };
    name: string;
    serviceName?: string;
    /**
     * OTLP signals: logs and/or traces
     */
    signals: Array<string> | null;
};

export type CreateInputBody3 = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    category?: 'bug' | 'idea' | 'praise' | 'other';
    context?: {
        [key: string]: unknown;
    };
    message: string;
};

export type CreateInputBody4 = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    company: string;
    email: string;
    name?: string;
    useCase: string;
};

export type CreateInvitationInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Email to invite
     */
    invitedEmail: string;
    /**
     * Role to grant on accept
     */
    role: 'user' | 'admin' | 'owner';
};

export type CreateOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    id: string;
};

export type CreateOutputBody1 = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    ok: boolean;
    requestId: string;
};

export type CreateRuleInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    action: 'allow' | 'redact' | 'block' | 'flag';
    /**
     * builtin detector name, or 'regex'/'keyword'/'tool_name'/'tool_arg'
     */
    detector: string;
    name: string;
    /**
     * regex/keyword; tool name for tool_name; a JSON-path expression for tool_arg (e.g. 'amount > 10000', 'account =~ ^ext-')
     */
    pattern?: string;
    /**
     * which part of the loop to evaluate (default request)
     */
    target?: 'request' | 'response' | 'tool_call';
};

export type CreateTokenInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Channel the token can ingest into
     */
    channelId: string;
    /**
     * Environment the token is bound to
     */
    environmentId: string;
    /**
     * Human-readable token label
     */
    name: string;
};

export type CreateTokenOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    active: boolean;
    appId?: string;
    channelId: string;
    createdAt: string;
    environmentId: string;
    lastUsedAt?: string;
    name: string;
    orgId: string;
    prefix: string;
    /**
     * The raw ingest token. Shown only once at creation.
     */
    token: string;
    tokenId: string;
};

export type DecisionDto = {
    appId?: string;
    budgetApproaching?: string;
    costUsd: number;
    enforcementAction?: string;
    eventType: string;
    model?: string;
    occurredAt: string;
    parentSpanId?: string;
    provider?: string;
    semanticKind?: string;
    spanId?: string;
    status?: string;
    toolName?: string;
    traceId?: string;
};

export type DeleteOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    deleted: boolean;
};

export type DeliveryDto = {
    attempts?: number;
    createdAt: string;
    deliveryId: string;
    endpointId: string;
    error?: string;
    eventId: string;
    nextRetryAt?: string;
    status?: string;
    statusCode?: number;
};

export type DestinationDto = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    active: boolean;
    createdAt: string;
    destinationId: string;
    endpointUrl: string;
    envSlug: string;
    eventTypeFilter: Array<string> | null;
    headerKeys: Array<string> | null;
    name: string;
    orgId: string;
    serviceName?: string;
    signals: Array<string> | null;
    updatedAt?: string;
};

export type EfficacyOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    rows: Array<EfficacyRowDto> | null;
};

export type EfficacyRowDto = {
    action: string;
    avgLatencyMs: number;
    detector: string;
    maxLatencyMs: number;
    target: string;
    violationCount: number;
};

export type EndpointDto = {
    active: boolean;
    channelId: string;
    createdAt: string;
    description?: string;
    endpointId: string;
    eventTypes: Array<string> | null;
    hasSecret: boolean;
    orgId?: string;
    updatedAt?: string;
    url: string;
};

export type EnvironmentDto = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    color: string;
    createdAt: string;
    environmentId: string;
    expiresAt?: string;
    isDefault: boolean;
    isEphemeral: boolean;
    isProduction: boolean;
    name: string;
    orgId: string;
    slug: string;
    updatedAt?: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type EventBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    agentId?: string;
    /**
     * Target channel id
     */
    channel_id: string;
    dedupKey?: string;
    /**
     * Canonical event type; defaults to custom
     */
    eventType?: string;
    /**
     * Event identifier / operation name
     */
    identifier: string;
    metadata?: {
        [key: string]: unknown;
    };
    parentSpanId?: string;
    /**
     * Event payload
     */
    payload: {
        [key: string]: unknown;
    };
    spanId?: string;
    /**
     * Ignored; ingest is always asynchronous
     */
    sync?: boolean;
    traceId?: string;
};

export type EventDto = {
    agentId?: string;
    agentName?: string;
    appId: string;
    attributes?: unknown;
    cacheReadTokens?: number;
    cacheWriteTokens?: number;
    channelId: string;
    costSource?: string;
    costUsd?: number;
    createdAt: string;
    durationMs?: number;
    environmentId?: string;
    errorMessage?: string;
    errorType?: string;
    eventId: string;
    eventType: string;
    finishReason?: string;
    inputTokens?: number;
    metadata?: unknown;
    occurredAt: string;
    operationName?: string;
    orgId: string;
    outputTokens?: number;
    parentSpanId?: string;
    payload?: unknown;
    payloadSpilled: boolean;
    providerName?: string;
    reasoningTokens?: number;
    requestModel?: string;
    resourceAttributes?: unknown;
    responseModel?: string;
    semanticKind?: string;
    serviceName?: string;
    sessionId?: string;
    source: string;
    spanId?: string;
    status?: string;
    toolName?: string;
    totalTokens?: number;
    traceId?: string;
    ttftMs?: number;
    userId?: string;
};

export type EventOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    eventId: string;
    status: string;
};

export type FeatureFlags = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    asyncIngest: boolean;
    environments: boolean;
    mcpServer: boolean;
    sentryIngest: boolean;
};

export type FeedbackDto = {
    category?: string;
    context?: unknown;
    createdAt: string;
    email?: string;
    feedbackId: string;
    message: string;
    orgId?: string;
    reviewedAt?: string;
    reviewedBy?: string;
    status: string;
    userId?: string;
};

export type GetOrgOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    invitations: Array<OrgInvitationDto> | null;
    members: Array<OrgMemberDto> | null;
    org: OrgDto;
};

export type GetOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    decisions: Array<DecisionDto> | null;
};

export type GetTraceOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    spans: Array<EventDto> | null;
    traceId: string;
};

export type HealthOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Entrypoint name
     */
    service: string;
    /**
     * Service health status
     */
    status: string;
    /**
     * Build version
     */
    version: string;
};

export type InvitationDto = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    code: string;
    createdAt: string;
    expiresAt?: string;
    invitationId: string;
    inviteRole: string;
    invitedEmail: string;
    inviterId?: string;
    orgId: string;
    status: string;
};

export type LicenseOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    edition: string;
    expiresAt?: string;
    message?: string;
    status: string;
    tier?: string;
};

export type LicenseStatus = {
    expiresAt: string | null;
    status: string;
    tier: string | null;
};

export type LinkOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    url: string;
};

export type ListAbuseFlagsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    flags: Array<AbuseFlagDto> | null;
};

export type ListAccessRequestsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    requests: Array<AccessRequestDto> | null;
};

export type ListAppsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    apps: Array<AppDto> | null;
};

export type ListBillingEventsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    events: Array<BillingEventDto> | null;
};

export type ListChannelsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    channels: Array<ChannelDto> | null;
};

export type ListDeliveriesOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    data: Array<DeliveryDto> | null;
};

export type ListEndpointsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    data: Array<EndpointDto> | null;
};

export type ListEnvironmentsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    environments: Array<EnvironmentDto> | null;
};

export type ListFeedbackOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<FeedbackDto> | null;
};

export type ListInvitationsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    invitations: Array<InvitationDto> | null;
};

export type ListMembersOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    members: Array<MemberDto> | null;
};

export type ListOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    budgets: Array<CostBudget> | null;
};

export type ListOutputBody1 = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    data: Array<AlertRuleDto> | null;
};

export type ListOutputBody2 = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    data: Array<DestinationDto> | null;
};

export type ListOutputBody3 = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    data: Array<LogDto> | null;
};

export type ListRulesOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    rules: Array<RuleDto> | null;
};

export type ListTokensOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    tokens: Array<PublicIngestTokenDto> | null;
};

export type ListTracesOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    traces: Array<TraceSummaryDto> | null;
};

export type ListViolationsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    violations: Array<ViolationDto> | null;
};

export type LogDto = {
    action: string;
    actorEmail?: string;
    actorId: string | null;
    createdAt: string;
    id: string;
    ipAddress: string | null;
    metadata: unknown;
    organizationId: string;
    resourceId: string;
    resourceType: string;
};

export type MeDto = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    authMethod: string;
    email?: string;
    emailVerified: boolean;
    memberships: Array<MembershipDto> | null;
    orgId: string;
    roles: Array<string> | null;
    userId?: string;
};

export type MemberDto = {
    email?: string;
    joinedAt: string;
    memberId: string;
    orgId: string;
    role: string;
    userId: string;
};

export type MembershipDto = {
    orgId: string;
    role: string;
};

export type MessageOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type ModerationCapability = {
    actions: Array<string> | null;
    detectors: Array<string> | null;
    enabled: boolean;
    targets: Array<string> | null;
};

export type OkOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    ok: boolean;
};

export type OrgDto = {
    billingMonthlyAmountUsd?: number;
    billingNotes?: string;
    createdAt: string;
    eventsQuotaMonthly?: number;
    eventsQuotaMonthlyOverride?: number;
    eventsQuotaUsedCurrent: number;
    name: string;
    orgId: string;
    plan: string;
    retentionDays?: number;
    retentionDaysOverride?: number;
    seatLimit?: number;
    seatLimitOverride?: number;
    slug: string;
    subscriptionStatus: string;
    trialEndsAt?: string;
    updatedAt?: string;
};

export type OrgInvitationDto = {
    code: string;
    createdAt: string;
    invitationId: string;
    inviteRole: string;
    invitedEmail: string;
    status: string;
};

export type OrgMemberDto = {
    joinedAt: string;
    role: string;
    userId: string;
};

export type OrganizationDto = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    createdAt: string;
    description?: string;
    eventsQuotaMonthly?: number;
    name: string;
    orgId: string;
    plan: string;
    retentionDays?: number;
    seatLimit?: number;
    slug: string;
    subscriptionStatus: string;
    updatedAt?: string;
};

export type OverviewOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    organizations: number;
};

export type PlanFeatures = {
    auditLog?: boolean;
    customRetention?: boolean;
    rbac?: boolean;
    sso?: boolean;
};

export type PlanLimits = {
    events: number | null;
    experimentsMonthly: number | null;
    features: PlanFeatures;
    hotRetentionDays: number | null;
    lemonsqueezyVariants?: {
        [key: string]: string;
    };
    priceAnnualUsd: number | null;
    priceMonthlyUsd: number | null;
    retentionDays: number | null;
    seats: number | null;
};

export type PlansOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    plans: {
        [key: string]: PlanLimits;
    };
};

export type PublicIngestTokenDto = {
    active: boolean;
    appId?: string;
    channelId: string;
    createdAt: string;
    environmentId: string;
    lastUsedAt?: string;
    name: string;
    orgId: string;
    prefix: string;
    tokenId: string;
};

export type RuleDto = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    action: string;
    createdAt: string;
    detector: string;
    enabled: boolean;
    name: string;
    pattern: string;
    ruleId: string;
    target: string;
};

export type SearchEventsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    events: Array<EventDto> | null;
};

export type SearchOrgsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    orgs: Array<OrgDto> | null;
};

export type SearchUsersOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    users: Array<UserDto> | null;
};

export type SetAccessRequestStatusInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    status: string;
};

export type SetActiveOrgInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Organization to make active
     */
    orgId: string;
};

export type SetFeedbackStatusInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    status: string;
};

export type SetLimitsInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    eventsQuotaMonthlyOverride?: number;
    retentionDaysOverride?: number;
    /**
     * -1 = unlimited, null clears the override
     */
    seatLimitOverride?: number;
};

export type SetPlanInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    plan: string;
};

export type SetStatusInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    subscriptionStatus: string;
};

export type SetTrialInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Trial length in days from now
     */
    days: number;
};

export type TelemetryPolicyOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    policy: unknown;
    version: number;
};

export type TimeseriesOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bucket: string;
    points: Array<TimeseriesPointDto> | null;
};

export type TimeseriesPointDto = {
    avgDurationMs: number;
    bucket: string;
    costUsd: number;
    errorCount: number;
    eventCount: number;
    totalTokens: number;
    traceCount: number;
};

export type TraceSummaryDto = {
    costUsd: number;
    durationMs: number;
    endedAt: string;
    errorCount: number;
    models: Array<string> | null;
    providers: Array<string> | null;
    spanCount: number;
    startedAt: string;
    totalTokens: number;
    traceId: string;
};

export type TransferOwnershipInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Member to promote to owner
     */
    userId: string;
};

export type UpdateAppInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type UpdateChannelInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type UpdateEnvironmentInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    color?: string;
    isProduction?: boolean;
    name?: string;
};

export type UpdateInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    appId?: string;
    dailyLimitUsd?: number;
    enabled?: boolean;
    monthlyLimitUsd?: number;
    name?: string;
};

export type UpdateInputBody1 = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    destination?: string;
    destinationType?: 'email' | 'webhook';
    enabled?: boolean;
    metric?: 'error_count' | 'error_rate' | 'latency_ms' | 'cost_usd' | 'score';
    name?: string;
    operator?: 'gt' | 'gte' | 'lt' | 'lte';
    threshold?: number;
};

export type UpdateInputBody2 = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    active?: boolean;
    endpointUrl?: string;
    eventTypeFilter?: Array<string>;
    /**
     * Replaces the stored header map. Never returned.
     */
    headers?: {
        [key: string]: string;
    };
    name?: string;
    serviceName?: string;
    signals?: Array<string>;
};

export type UpdateMemberRoleInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    role: 'user' | 'admin' | 'owner';
};

export type UpdateOrganizationInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description?: string;
    name?: string;
};

export type UpdateProfileInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    firstName?: string;
    lastName?: string;
};

export type UsageOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    cycleStartedAt: string | null;
    hasBillingPortal: boolean;
    limit: number | null;
    plan: string;
    retentionDays: number | null;
    seats: number | null;
    subscriptionStatus: string;
    trialEndsAt: string | null;
    used: number;
};

export type UserDto = {
    disabledAt?: string;
    email: string;
    firstName?: string;
    id: string;
    lastName?: string;
    organizationId?: string;
    username?: string;
};

export type UserOrgDto = {
    organization: OrganizationDto;
    role: string;
};

export type UserOrgsOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    organizations: Array<UserOrgDto> | null;
};

export type ViolationDto = {
    action: string;
    appId?: string;
    channelId?: string;
    detector: string;
    occurredAt: string;
    ruleId: string;
    ruleName: string;
    violationId: string;
};

export type WebhookOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    deduped?: boolean;
    ok: boolean;
    skipped?: string;
};

export type AlertRuleDtoWritable = {
    alertRuleId: string;
    appId?: string;
    createdAt: string;
    destination: string;
    destinationType: string;
    enabled: boolean;
    environmentId?: string;
    metric: string;
    model?: string;
    name: string;
    operator: string;
    orgId: string;
    release?: string;
    service?: string;
    threshold: number;
    updatedAt: string;
};

export type AppDtoWritable = {
    appId: string;
    createdAt: string;
    creatorUserId?: string;
    name: string;
    orgId: string;
    updatedAt?: string;
};

export type BreakdownOutputBodyWritable = {
    dimension: string;
    rows: Array<BreakdownRowDto> | null;
};

export type CapabilitiesOutputBodyWritable = {
    apiKeyScopes: Array<ApiKeyScope> | null;
    controls: Controls;
    featureFlags: FeatureFlagsWritable;
    license: LicenseStatus;
    version: string;
};

export type ChannelDtoWritable = {
    appId: string;
    channelId: string;
    createdAt: string;
    name: string;
    orgId: string;
    updatedAt?: string;
};

export type CheckoutInputBodyWritable = {
    /**
     * monthly or annual
     */
    cadence?: string;
    /**
     * pro or team
     */
    plan: string;
};

export type CostBudgetWritable = {
    appId?: string;
    budgetId: string;
    createdAt: string;
    dailyLimitUsd: number;
    enabled: boolean;
    monthlyLimitUsd: number;
    name: string;
    updatedAt: string;
};

export type CreateAppInputBodyWritable = {
    /**
     * App display name
     */
    name: string;
};

export type CreateChannelInputBodyWritable = {
    /**
     * Channel name
     */
    name: string;
};

export type CreateEndpointInputBodyWritable = {
    channelId: string;
    description?: string;
    /**
     * Event types to filter (empty = all)
     */
    eventTypes?: Array<string> | null;
    url: string;
};

export type CreateEndpointOutputBodyWritable = {
    active: boolean;
    channelId: string;
    createdAt: string;
    description?: string;
    endpointId: string;
    eventTypes: Array<string> | null;
    hasSecret: boolean;
    orgId?: string;
    /**
     * Signing secret, only returned at creation time
     */
    rawSecret: string;
    updatedAt?: string;
    url: string;
};

export type CreateEnvironmentInputBodyWritable = {
    color?: string;
    isDefault?: boolean;
    isProduction?: boolean;
    /**
     * Environment display name
     */
    name: string;
    /**
     * URL-safe slug; derived from name when omitted
     */
    slug?: string;
};

export type CreateInputBodyWritable = {
    /**
     * scope to an app; empty means org-wide
     */
    appId?: string;
    /**
     * per-UTC-day ceiling in USD; 0 disables the daily cap
     */
    dailyLimitUsd?: number;
    /**
     * per-UTC-month ceiling in USD; 0 disables the monthly cap
     */
    monthlyLimitUsd?: number;
    name: string;
};

export type CreateInputBody1Writable = {
    appId?: string;
    destination: string;
    destinationType: 'email' | 'webhook';
    enabled?: boolean;
    environmentId?: string;
    metric: 'error_count' | 'error_rate' | 'latency_ms' | 'cost_usd' | 'score';
    model?: string;
    /**
     * Alert rule display name
     */
    name: string;
    operator: 'gt' | 'gte' | 'lt' | 'lte';
    release?: string;
    service?: string;
    threshold: number;
};

export type CreateInputBody2Writable = {
    endpointUrl: string;
    envSlug: string;
    eventTypeFilter?: Array<string> | null;
    /**
     * Header name -> value map. Stored server-side, never returned.
     */
    headers?: {
        [key: string]: string;
    };
    name: string;
    serviceName?: string;
    /**
     * OTLP signals: logs and/or traces
     */
    signals: Array<string> | null;
};

export type CreateInputBody3Writable = {
    category?: 'bug' | 'idea' | 'praise' | 'other';
    context?: {
        [key: string]: unknown;
    };
    message: string;
};

export type CreateInputBody4Writable = {
    company: string;
    email: string;
    name?: string;
    useCase: string;
};

export type CreateInvitationInputBodyWritable = {
    /**
     * Email to invite
     */
    invitedEmail: string;
    /**
     * Role to grant on accept
     */
    role: 'user' | 'admin' | 'owner';
};

export type CreateOutputBodyWritable = {
    id: string;
};

export type CreateOutputBody1Writable = {
    ok: boolean;
    requestId: string;
};

export type CreateRuleInputBodyWritable = {
    action: 'allow' | 'redact' | 'block' | 'flag';
    /**
     * builtin detector name, or 'regex'/'keyword'/'tool_name'/'tool_arg'
     */
    detector: string;
    name: string;
    /**
     * regex/keyword; tool name for tool_name; a JSON-path expression for tool_arg (e.g. 'amount > 10000', 'account =~ ^ext-')
     */
    pattern?: string;
    /**
     * which part of the loop to evaluate (default request)
     */
    target?: 'request' | 'response' | 'tool_call';
};

export type CreateTokenInputBodyWritable = {
    /**
     * Channel the token can ingest into
     */
    channelId: string;
    /**
     * Environment the token is bound to
     */
    environmentId: string;
    /**
     * Human-readable token label
     */
    name: string;
};

export type CreateTokenOutputBodyWritable = {
    active: boolean;
    appId?: string;
    channelId: string;
    createdAt: string;
    environmentId: string;
    lastUsedAt?: string;
    name: string;
    orgId: string;
    prefix: string;
    /**
     * The raw ingest token. Shown only once at creation.
     */
    token: string;
    tokenId: string;
};

export type DeleteOutputBodyWritable = {
    deleted: boolean;
};

export type DestinationDtoWritable = {
    active: boolean;
    createdAt: string;
    destinationId: string;
    endpointUrl: string;
    envSlug: string;
    eventTypeFilter: Array<string> | null;
    headerKeys: Array<string> | null;
    name: string;
    orgId: string;
    serviceName?: string;
    signals: Array<string> | null;
    updatedAt?: string;
};

export type EfficacyOutputBodyWritable = {
    rows: Array<EfficacyRowDto> | null;
};

export type EnvironmentDtoWritable = {
    color: string;
    createdAt: string;
    environmentId: string;
    expiresAt?: string;
    isDefault: boolean;
    isEphemeral: boolean;
    isProduction: boolean;
    name: string;
    orgId: string;
    slug: string;
    updatedAt?: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type EventBodyWritable = {
    agentId?: string;
    /**
     * Target channel id
     */
    channel_id: string;
    dedupKey?: string;
    /**
     * Canonical event type; defaults to custom
     */
    eventType?: string;
    /**
     * Event identifier / operation name
     */
    identifier: string;
    metadata?: {
        [key: string]: unknown;
    };
    parentSpanId?: string;
    /**
     * Event payload
     */
    payload: {
        [key: string]: unknown;
    };
    spanId?: string;
    /**
     * Ignored; ingest is always asynchronous
     */
    sync?: boolean;
    traceId?: string;
};

export type EventOutputBodyWritable = {
    eventId: string;
    status: string;
};

export type FeatureFlagsWritable = {
    asyncIngest: boolean;
    environments: boolean;
    mcpServer: boolean;
    sentryIngest: boolean;
};

export type GetOrgOutputBodyWritable = {
    invitations: Array<OrgInvitationDto> | null;
    members: Array<OrgMemberDto> | null;
    org: OrgDto;
};

export type GetOutputBodyWritable = {
    decisions: Array<DecisionDto> | null;
};

export type GetTraceOutputBodyWritable = {
    spans: Array<EventDto> | null;
    traceId: string;
};

export type HealthOutputBodyWritable = {
    /**
     * Entrypoint name
     */
    service: string;
    /**
     * Service health status
     */
    status: string;
    /**
     * Build version
     */
    version: string;
};

export type InvitationDtoWritable = {
    code: string;
    createdAt: string;
    expiresAt?: string;
    invitationId: string;
    inviteRole: string;
    invitedEmail: string;
    inviterId?: string;
    orgId: string;
    status: string;
};

export type LicenseOutputBodyWritable = {
    edition: string;
    expiresAt?: string;
    message?: string;
    status: string;
    tier?: string;
};

export type LinkOutputBodyWritable = {
    url: string;
};

export type ListAbuseFlagsOutputBodyWritable = {
    flags: Array<AbuseFlagDto> | null;
};

export type ListAccessRequestsOutputBodyWritable = {
    requests: Array<AccessRequestDto> | null;
};

export type ListAppsOutputBodyWritable = {
    apps: Array<AppDtoWritable> | null;
};

export type ListBillingEventsOutputBodyWritable = {
    events: Array<BillingEventDto> | null;
};

export type ListChannelsOutputBodyWritable = {
    channels: Array<ChannelDtoWritable> | null;
};

export type ListDeliveriesOutputBodyWritable = {
    data: Array<DeliveryDto> | null;
};

export type ListEndpointsOutputBodyWritable = {
    data: Array<EndpointDto> | null;
};

export type ListEnvironmentsOutputBodyWritable = {
    environments: Array<EnvironmentDtoWritable> | null;
};

export type ListFeedbackOutputBodyWritable = {
    items: Array<FeedbackDto> | null;
};

export type ListInvitationsOutputBodyWritable = {
    invitations: Array<InvitationDtoWritable> | null;
};

export type ListMembersOutputBodyWritable = {
    members: Array<MemberDto> | null;
};

export type ListOutputBodyWritable = {
    budgets: Array<CostBudgetWritable> | null;
};

export type ListOutputBody1Writable = {
    data: Array<AlertRuleDtoWritable> | null;
};

export type ListOutputBody2Writable = {
    data: Array<DestinationDtoWritable> | null;
};

export type ListOutputBody3Writable = {
    data: Array<LogDto> | null;
};

export type ListRulesOutputBodyWritable = {
    rules: Array<RuleDtoWritable> | null;
};

export type ListTokensOutputBodyWritable = {
    tokens: Array<PublicIngestTokenDto> | null;
};

export type ListTracesOutputBodyWritable = {
    traces: Array<TraceSummaryDto> | null;
};

export type ListViolationsOutputBodyWritable = {
    violations: Array<ViolationDto> | null;
};

export type MeDtoWritable = {
    authMethod: string;
    email?: string;
    emailVerified: boolean;
    memberships: Array<MembershipDto> | null;
    orgId: string;
    roles: Array<string> | null;
    userId?: string;
};

export type MessageOutputBodyWritable = {
    message: string;
};

export type OkOutputBodyWritable = {
    ok: boolean;
};

export type OrganizationDtoWritable = {
    createdAt: string;
    description?: string;
    eventsQuotaMonthly?: number;
    name: string;
    orgId: string;
    plan: string;
    retentionDays?: number;
    seatLimit?: number;
    slug: string;
    subscriptionStatus: string;
    updatedAt?: string;
};

export type OverviewOutputBodyWritable = {
    organizations: number;
};

export type PlansOutputBodyWritable = {
    plans: {
        [key: string]: PlanLimits;
    };
};

export type RuleDtoWritable = {
    action: string;
    createdAt: string;
    detector: string;
    enabled: boolean;
    name: string;
    pattern: string;
    ruleId: string;
    target: string;
};

export type SearchEventsOutputBodyWritable = {
    events: Array<EventDto> | null;
};

export type SearchOrgsOutputBodyWritable = {
    orgs: Array<OrgDto> | null;
};

export type SearchUsersOutputBodyWritable = {
    users: Array<UserDto> | null;
};

export type SetAccessRequestStatusInputBodyWritable = {
    status: string;
};

export type SetActiveOrgInputBodyWritable = {
    /**
     * Organization to make active
     */
    orgId: string;
};

export type SetFeedbackStatusInputBodyWritable = {
    status: string;
};

export type SetLimitsInputBodyWritable = {
    eventsQuotaMonthlyOverride?: number;
    retentionDaysOverride?: number;
    /**
     * -1 = unlimited, null clears the override
     */
    seatLimitOverride?: number;
};

export type SetPlanInputBodyWritable = {
    plan: string;
};

export type SetStatusInputBodyWritable = {
    subscriptionStatus: string;
};

export type SetTrialInputBodyWritable = {
    /**
     * Trial length in days from now
     */
    days: number;
};

export type TelemetryPolicyOutputBodyWritable = {
    policy: unknown;
    version: number;
};

export type TimeseriesOutputBodyWritable = {
    bucket: string;
    points: Array<TimeseriesPointDto> | null;
};

export type TransferOwnershipInputBodyWritable = {
    /**
     * Member to promote to owner
     */
    userId: string;
};

export type UpdateAppInputBodyWritable = {
    name: string;
};

export type UpdateChannelInputBodyWritable = {
    name: string;
};

export type UpdateEnvironmentInputBodyWritable = {
    color?: string;
    isProduction?: boolean;
    name?: string;
};

export type UpdateInputBodyWritable = {
    appId?: string;
    dailyLimitUsd?: number;
    enabled?: boolean;
    monthlyLimitUsd?: number;
    name?: string;
};

export type UpdateInputBody1Writable = {
    destination?: string;
    destinationType?: 'email' | 'webhook';
    enabled?: boolean;
    metric?: 'error_count' | 'error_rate' | 'latency_ms' | 'cost_usd' | 'score';
    name?: string;
    operator?: 'gt' | 'gte' | 'lt' | 'lte';
    threshold?: number;
};

export type UpdateInputBody2Writable = {
    active?: boolean;
    endpointUrl?: string;
    eventTypeFilter?: Array<string>;
    /**
     * Replaces the stored header map. Never returned.
     */
    headers?: {
        [key: string]: string;
    };
    name?: string;
    serviceName?: string;
    signals?: Array<string>;
};

export type UpdateMemberRoleInputBodyWritable = {
    role: 'user' | 'admin' | 'owner';
};

export type UpdateOrganizationInputBodyWritable = {
    description?: string;
    name?: string;
};

export type UpdateProfileInputBodyWritable = {
    firstName?: string;
    lastName?: string;
};

export type UsageOutputBodyWritable = {
    cycleStartedAt: string | null;
    hasBillingPortal: boolean;
    limit: number | null;
    plan: string;
    retentionDays: number | null;
    seats: number | null;
    subscriptionStatus: string;
    trialEndsAt: string | null;
    used: number;
};

export type UserOrgDtoWritable = {
    organization: OrganizationDtoWritable;
    role: string;
};

export type UserOrgsOutputBodyWritable = {
    organizations: Array<UserOrgDtoWritable> | null;
};

export type WebhookOutputBodyWritable = {
    deduped?: boolean;
    ok: boolean;
    skipped?: string;
};

export type AccessRequestCreateData = {
    body: CreateInputBody4Writable;
    headers?: {
        'CF-Connecting-IP'?: string;
        'X-Forwarded-For'?: string;
        'X-Real-IP'?: string;
        'User-Agent'?: string;
        'CF-IPCountry'?: string;
    };
    path?: never;
    query?: never;
    url: '/access-requests';
};

export type AccessRequestCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AccessRequestCreateError = AccessRequestCreateErrors[keyof AccessRequestCreateErrors];

export type AccessRequestCreateResponses = {
    /**
     * Created
     */
    201: CreateOutputBody1;
};

export type AccessRequestCreateResponse = AccessRequestCreateResponses[keyof AccessRequestCreateResponses];

export type AdminAbuseFlagsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by status
         */
        status?: string;
    };
    url: '/admin/abuse-flags';
};

export type AdminAbuseFlagsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminAbuseFlagsListError = AdminAbuseFlagsListErrors[keyof AdminAbuseFlagsListErrors];

export type AdminAbuseFlagsListResponses = {
    /**
     * OK
     */
    200: ListAbuseFlagsOutputBody;
};

export type AdminAbuseFlagsListResponse = AdminAbuseFlagsListResponses[keyof AdminAbuseFlagsListResponses];

export type AdminAbuseFlagsReviewData = {
    body?: never;
    path: {
        flagId: string;
    };
    query?: never;
    url: '/admin/abuse-flags/{flagId}/dismiss';
};

export type AdminAbuseFlagsReviewErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminAbuseFlagsReviewError = AdminAbuseFlagsReviewErrors[keyof AdminAbuseFlagsReviewErrors];

export type AdminAbuseFlagsReviewResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type AdminAbuseFlagsReviewResponse = AdminAbuseFlagsReviewResponses[keyof AdminAbuseFlagsReviewResponses];

export type AdminAccessRequestsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by status
         */
        status?: string;
    };
    url: '/admin/access-requests';
};

export type AdminAccessRequestsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminAccessRequestsListError = AdminAccessRequestsListErrors[keyof AdminAccessRequestsListErrors];

export type AdminAccessRequestsListResponses = {
    /**
     * OK
     */
    200: ListAccessRequestsOutputBody;
};

export type AdminAccessRequestsListResponse = AdminAccessRequestsListResponses[keyof AdminAccessRequestsListResponses];

export type AdminAccessRequestsSetStatusData = {
    body: SetAccessRequestStatusInputBodyWritable;
    path: {
        requestId: string;
    };
    query?: never;
    url: '/admin/access-requests/{requestId}/status';
};

export type AdminAccessRequestsSetStatusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminAccessRequestsSetStatusError = AdminAccessRequestsSetStatusErrors[keyof AdminAccessRequestsSetStatusErrors];

export type AdminAccessRequestsSetStatusResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type AdminAccessRequestsSetStatusResponse = AdminAccessRequestsSetStatusResponses[keyof AdminAccessRequestsSetStatusResponses];

export type AdminBillingEventsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/billing-events';
};

export type AdminBillingEventsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminBillingEventsListError = AdminBillingEventsListErrors[keyof AdminBillingEventsListErrors];

export type AdminBillingEventsListResponses = {
    /**
     * OK
     */
    200: ListBillingEventsOutputBody;
};

export type AdminBillingEventsListResponse = AdminBillingEventsListResponses[keyof AdminBillingEventsListResponses];

export type AdminFeedbackListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by status
         */
        status?: string;
    };
    url: '/admin/feedback';
};

export type AdminFeedbackListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminFeedbackListError = AdminFeedbackListErrors[keyof AdminFeedbackListErrors];

export type AdminFeedbackListResponses = {
    /**
     * OK
     */
    200: ListFeedbackOutputBody;
};

export type AdminFeedbackListResponse = AdminFeedbackListResponses[keyof AdminFeedbackListResponses];

export type AdminFeedbackSetStatusData = {
    body: SetFeedbackStatusInputBodyWritable;
    path: {
        feedbackId: string;
    };
    query?: never;
    url: '/admin/feedback/{feedbackId}/status';
};

export type AdminFeedbackSetStatusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminFeedbackSetStatusError = AdminFeedbackSetStatusErrors[keyof AdminFeedbackSetStatusErrors];

export type AdminFeedbackSetStatusResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type AdminFeedbackSetStatusResponse = AdminFeedbackSetStatusResponses[keyof AdminFeedbackSetStatusResponses];

export type AdminOrgsSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by name or slug
         */
        q?: string;
    };
    url: '/admin/orgs';
};

export type AdminOrgsSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminOrgsSearchError = AdminOrgsSearchErrors[keyof AdminOrgsSearchErrors];

export type AdminOrgsSearchResponses = {
    /**
     * OK
     */
    200: SearchOrgsOutputBody;
};

export type AdminOrgsSearchResponse = AdminOrgsSearchResponses[keyof AdminOrgsSearchResponses];

export type AdminOrgsGetData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}';
};

export type AdminOrgsGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminOrgsGetError = AdminOrgsGetErrors[keyof AdminOrgsGetErrors];

export type AdminOrgsGetResponses = {
    /**
     * OK
     */
    200: GetOrgOutputBody;
};

export type AdminOrgsGetResponse = AdminOrgsGetResponses[keyof AdminOrgsGetResponses];

export type AdminOrgsSetLimitsData = {
    body: SetLimitsInputBodyWritable;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/limits';
};

export type AdminOrgsSetLimitsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminOrgsSetLimitsError = AdminOrgsSetLimitsErrors[keyof AdminOrgsSetLimitsErrors];

export type AdminOrgsSetLimitsResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type AdminOrgsSetLimitsResponse = AdminOrgsSetLimitsResponses[keyof AdminOrgsSetLimitsResponses];

export type AdminOrgsSetPlanData = {
    body: SetPlanInputBodyWritable;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/plan';
};

export type AdminOrgsSetPlanErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminOrgsSetPlanError = AdminOrgsSetPlanErrors[keyof AdminOrgsSetPlanErrors];

export type AdminOrgsSetPlanResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type AdminOrgsSetPlanResponse = AdminOrgsSetPlanResponses[keyof AdminOrgsSetPlanResponses];

export type AdminOrgsSetStatusData = {
    body: SetStatusInputBodyWritable;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/status';
};

export type AdminOrgsSetStatusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminOrgsSetStatusError = AdminOrgsSetStatusErrors[keyof AdminOrgsSetStatusErrors];

export type AdminOrgsSetStatusResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type AdminOrgsSetStatusResponse = AdminOrgsSetStatusResponses[keyof AdminOrgsSetStatusResponses];

export type AdminOrgsSetTrialData = {
    body: SetTrialInputBodyWritable;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/trial';
};

export type AdminOrgsSetTrialErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminOrgsSetTrialError = AdminOrgsSetTrialErrors[keyof AdminOrgsSetTrialErrors];

export type AdminOrgsSetTrialResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type AdminOrgsSetTrialResponse = AdminOrgsSetTrialResponses[keyof AdminOrgsSetTrialResponses];

export type AdminOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/overview';
};

export type AdminOverviewErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminOverviewError = AdminOverviewErrors[keyof AdminOverviewErrors];

export type AdminOverviewResponses = {
    /**
     * OK
     */
    200: OverviewOutputBody;
};

export type AdminOverviewResponse = AdminOverviewResponses[keyof AdminOverviewResponses];

export type AdminUsersSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by email or username
         */
        q?: string;
    };
    url: '/admin/users';
};

export type AdminUsersSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminUsersSearchError = AdminUsersSearchErrors[keyof AdminUsersSearchErrors];

export type AdminUsersSearchResponses = {
    /**
     * OK
     */
    200: SearchUsersOutputBody;
};

export type AdminUsersSearchResponse = AdminUsersSearchResponses[keyof AdminUsersSearchResponses];

export type AdminUsersDisableData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/admin/users/{userId}/disable';
};

export type AdminUsersDisableErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminUsersDisableError = AdminUsersDisableErrors[keyof AdminUsersDisableErrors];

export type AdminUsersDisableResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type AdminUsersDisableResponse = AdminUsersDisableResponses[keyof AdminUsersDisableResponses];

export type AdminUsersEnableData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/admin/users/{userId}/enable';
};

export type AdminUsersEnableErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AdminUsersEnableError = AdminUsersEnableErrors[keyof AdminUsersEnableErrors];

export type AdminUsersEnableResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type AdminUsersEnableResponse = AdminUsersEnableResponses[keyof AdminUsersEnableResponses];

export type AnalyticsBreakdownData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Window start (RFC3339); defaults to 24h before until
         */
        since?: string;
        /**
         * Window end (RFC3339); defaults to now
         */
        until?: string;
        /**
         * Breakdown dimension (default model)
         */
        dimension?: 'model' | 'provider' | 'agent' | 'tool';
        /**
         * Top-N entries (default 50, max 500)
         */
        limit?: number;
    };
    url: '/analytics/breakdown';
};

export type AnalyticsBreakdownErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalyticsBreakdownError = AnalyticsBreakdownErrors[keyof AnalyticsBreakdownErrors];

export type AnalyticsBreakdownResponses = {
    /**
     * OK
     */
    200: BreakdownOutputBody;
};

export type AnalyticsBreakdownResponse = AnalyticsBreakdownResponses[keyof AnalyticsBreakdownResponses];

export type AnalyticsTimeseriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Window start (RFC3339); defaults to 24h before until
         */
        since?: string;
        /**
         * Window end (RFC3339); defaults to now
         */
        until?: string;
        /**
         * Time bucket granularity (default hour)
         */
        bucket?: 'hour' | 'day';
    };
    url: '/analytics/timeseries';
};

export type AnalyticsTimeseriesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalyticsTimeseriesError = AnalyticsTimeseriesErrors[keyof AnalyticsTimeseriesErrors];

export type AnalyticsTimeseriesResponses = {
    /**
     * OK
     */
    200: TimeseriesOutputBody;
};

export type AnalyticsTimeseriesResponse = AnalyticsTimeseriesResponses[keyof AnalyticsTimeseriesResponses];

export type AppsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/apps';
};

export type AppsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AppsListError = AppsListErrors[keyof AppsListErrors];

export type AppsListResponses = {
    /**
     * OK
     */
    200: ListAppsOutputBody;
};

export type AppsListResponse = AppsListResponses[keyof AppsListResponses];

export type AppsCreateData = {
    body: CreateAppInputBodyWritable;
    path?: never;
    query?: never;
    url: '/apps';
};

export type AppsCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AppsCreateError = AppsCreateErrors[keyof AppsCreateErrors];

export type AppsCreateResponses = {
    /**
     * Created
     */
    201: AppDto;
};

export type AppsCreateResponse = AppsCreateResponses[keyof AppsCreateResponses];

export type AppsDeleteData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}';
};

export type AppsDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AppsDeleteError = AppsDeleteErrors[keyof AppsDeleteErrors];

export type AppsDeleteResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type AppsDeleteResponse = AppsDeleteResponses[keyof AppsDeleteResponses];

export type AppsGetData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}';
};

export type AppsGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AppsGetError = AppsGetErrors[keyof AppsGetErrors];

export type AppsGetResponses = {
    /**
     * OK
     */
    200: AppDto;
};

export type AppsGetResponse = AppsGetResponses[keyof AppsGetResponses];

export type AppsUpdateData = {
    body: UpdateAppInputBodyWritable;
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}';
};

export type AppsUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AppsUpdateError = AppsUpdateErrors[keyof AppsUpdateErrors];

export type AppsUpdateResponses = {
    /**
     * OK
     */
    200: AppDto;
};

export type AppsUpdateResponse = AppsUpdateResponses[keyof AppsUpdateResponses];

export type ChannelsListData = {
    body?: never;
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}/channels';
};

export type ChannelsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ChannelsListError = ChannelsListErrors[keyof ChannelsListErrors];

export type ChannelsListResponses = {
    /**
     * OK
     */
    200: ListChannelsOutputBody;
};

export type ChannelsListResponse = ChannelsListResponses[keyof ChannelsListResponses];

export type ChannelsCreateData = {
    body: CreateChannelInputBodyWritable;
    path: {
        appId: string;
    };
    query?: never;
    url: '/apps/{appId}/channels';
};

export type ChannelsCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ChannelsCreateError = ChannelsCreateErrors[keyof ChannelsCreateErrors];

export type ChannelsCreateResponses = {
    /**
     * Created
     */
    201: ChannelDto;
};

export type ChannelsCreateResponse = ChannelsCreateResponses[keyof ChannelsCreateResponses];

export type ChannelsDeleteData = {
    body?: never;
    path: {
        appId: string;
        channelId: string;
    };
    query?: never;
    url: '/apps/{appId}/channels/{channelId}';
};

export type ChannelsDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ChannelsDeleteError = ChannelsDeleteErrors[keyof ChannelsDeleteErrors];

export type ChannelsDeleteResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type ChannelsDeleteResponse = ChannelsDeleteResponses[keyof ChannelsDeleteResponses];

export type ChannelsGetData = {
    body?: never;
    path: {
        appId: string;
        channelId: string;
    };
    query?: never;
    url: '/apps/{appId}/channels/{channelId}';
};

export type ChannelsGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ChannelsGetError = ChannelsGetErrors[keyof ChannelsGetErrors];

export type ChannelsGetResponses = {
    /**
     * OK
     */
    200: ChannelDto;
};

export type ChannelsGetResponse = ChannelsGetResponses[keyof ChannelsGetResponses];

export type ChannelsUpdateData = {
    body: UpdateChannelInputBodyWritable;
    path: {
        appId: string;
        channelId: string;
    };
    query?: never;
    url: '/apps/{appId}/channels/{channelId}';
};

export type ChannelsUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ChannelsUpdateError = ChannelsUpdateErrors[keyof ChannelsUpdateErrors];

export type ChannelsUpdateResponses = {
    /**
     * OK
     */
    200: ChannelDto;
};

export type ChannelsUpdateResponse = ChannelsUpdateResponses[keyof ChannelsUpdateResponses];

export type AuditListData = {
    body?: never;
    path?: never;
    query?: {
        action?: string;
        resourceType?: string;
        /**
         * RFC3339 upper bound (exclusive); defaults to now
         */
        before?: string;
        limit?: number;
    };
    url: '/audit-logs';
};

export type AuditListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AuditListError = AuditListErrors[keyof AuditListErrors];

export type AuditListResponses = {
    /**
     * OK
     */
    200: ListOutputBody3;
};

export type AuditListResponse = AuditListResponses[keyof AuditListResponses];

export type AudittrailGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Window start (RFC3339); defaults to 24h before until
         */
        since?: string;
        /**
         * Window end (RFC3339); defaults to now
         */
        until?: string;
        /**
         * Restrict to a single trace
         */
        traceId?: string;
        /**
         * Max rows (default 1000, max 10000)
         */
        limit?: number;
    };
    url: '/audit-trail';
};

export type AudittrailGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AudittrailGetError = AudittrailGetErrors[keyof AudittrailGetErrors];

export type AudittrailGetResponses = {
    /**
     * OK
     */
    200: GetOutputBody;
};

export type AudittrailGetResponse = AudittrailGetResponses[keyof AudittrailGetResponses];

export type BillingCheckoutData = {
    body: CheckoutInputBodyWritable;
    path?: never;
    query?: never;
    url: '/billing/checkout';
};

export type BillingCheckoutErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BillingCheckoutError = BillingCheckoutErrors[keyof BillingCheckoutErrors];

export type BillingCheckoutResponses = {
    /**
     * Created
     */
    201: LinkOutputBody;
};

export type BillingCheckoutResponse = BillingCheckoutResponses[keyof BillingCheckoutResponses];

export type BillingPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/billing/plans';
};

export type BillingPlansErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BillingPlansError = BillingPlansErrors[keyof BillingPlansErrors];

export type BillingPlansResponses = {
    /**
     * OK
     */
    200: PlansOutputBody;
};

export type BillingPlansResponse = BillingPlansResponses[keyof BillingPlansResponses];

export type BillingPortalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/billing/portal';
};

export type BillingPortalErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BillingPortalError = BillingPortalErrors[keyof BillingPortalErrors];

export type BillingPortalResponses = {
    /**
     * OK
     */
    200: LinkOutputBody;
};

export type BillingPortalResponse = BillingPortalResponses[keyof BillingPortalResponses];

export type BillingUsageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/billing/usage';
};

export type BillingUsageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BillingUsageError = BillingUsageErrors[keyof BillingUsageErrors];

export type BillingUsageResponses = {
    /**
     * OK
     */
    200: UsageOutputBody;
};

export type BillingUsageResponse = BillingUsageResponses[keyof BillingUsageResponses];

export type BillingWebhookData = {
    body: Blob | File;
    headers?: {
        'X-Signature'?: string;
    };
    path?: never;
    query?: never;
    url: '/billing/webhook';
};

export type BillingWebhookErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BillingWebhookError = BillingWebhookErrors[keyof BillingWebhookErrors];

export type BillingWebhookResponses = {
    /**
     * OK
     */
    200: WebhookOutputBody;
};

export type BillingWebhookResponse = BillingWebhookResponses[keyof BillingWebhookResponses];

export type BudgetsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/budgets';
};

export type BudgetsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BudgetsListError = BudgetsListErrors[keyof BudgetsListErrors];

export type BudgetsListResponses = {
    /**
     * OK
     */
    200: ListOutputBody;
};

export type BudgetsListResponse = BudgetsListResponses[keyof BudgetsListResponses];

export type BudgetsCreateData = {
    body: CreateInputBodyWritable;
    path?: never;
    query?: never;
    url: '/budgets';
};

export type BudgetsCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BudgetsCreateError = BudgetsCreateErrors[keyof BudgetsCreateErrors];

export type BudgetsCreateResponses = {
    /**
     * Created
     */
    201: CostBudget;
};

export type BudgetsCreateResponse = BudgetsCreateResponses[keyof BudgetsCreateResponses];

export type BudgetsDeleteData = {
    body?: never;
    path: {
        budgetId: string;
    };
    query?: never;
    url: '/budgets/{budgetId}';
};

export type BudgetsDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BudgetsDeleteError = BudgetsDeleteErrors[keyof BudgetsDeleteErrors];

export type BudgetsDeleteResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type BudgetsDeleteResponse = BudgetsDeleteResponses[keyof BudgetsDeleteResponses];

export type BudgetsUpdateData = {
    body: UpdateInputBodyWritable;
    path: {
        budgetId: string;
    };
    query?: never;
    url: '/budgets/{budgetId}';
};

export type BudgetsUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BudgetsUpdateError = BudgetsUpdateErrors[keyof BudgetsUpdateErrors];

export type BudgetsUpdateResponses = {
    /**
     * OK
     */
    200: CostBudget;
};

export type BudgetsUpdateResponse = BudgetsUpdateResponses[keyof BudgetsUpdateResponses];

export type CapabilitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/capabilities';
};

export type CapabilitiesGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CapabilitiesGetError = CapabilitiesGetErrors[keyof CapabilitiesGetErrors];

export type CapabilitiesGetResponses = {
    /**
     * OK
     */
    200: CapabilitiesOutputBody;
};

export type CapabilitiesGetResponse = CapabilitiesGetResponses[keyof CapabilitiesGetResponses];

export type EnvironmentsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/environments';
};

export type EnvironmentsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type EnvironmentsListError = EnvironmentsListErrors[keyof EnvironmentsListErrors];

export type EnvironmentsListResponses = {
    /**
     * OK
     */
    200: ListEnvironmentsOutputBody;
};

export type EnvironmentsListResponse = EnvironmentsListResponses[keyof EnvironmentsListResponses];

export type EnvironmentsCreateData = {
    body: CreateEnvironmentInputBodyWritable;
    path?: never;
    query?: never;
    url: '/environments';
};

export type EnvironmentsCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type EnvironmentsCreateError = EnvironmentsCreateErrors[keyof EnvironmentsCreateErrors];

export type EnvironmentsCreateResponses = {
    /**
     * Created
     */
    201: EnvironmentDto;
};

export type EnvironmentsCreateResponse = EnvironmentsCreateResponses[keyof EnvironmentsCreateResponses];

export type EnvironmentsDeleteData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/environments/{slug}';
};

export type EnvironmentsDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type EnvironmentsDeleteError = EnvironmentsDeleteErrors[keyof EnvironmentsDeleteErrors];

export type EnvironmentsDeleteResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type EnvironmentsDeleteResponse = EnvironmentsDeleteResponses[keyof EnvironmentsDeleteResponses];

export type EnvironmentsUpdateData = {
    body: UpdateEnvironmentInputBodyWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/environments/{slug}';
};

export type EnvironmentsUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type EnvironmentsUpdateError = EnvironmentsUpdateErrors[keyof EnvironmentsUpdateErrors];

export type EnvironmentsUpdateResponses = {
    /**
     * OK
     */
    200: EnvironmentDto;
};

export type EnvironmentsUpdateResponse = EnvironmentsUpdateResponses[keyof EnvironmentsUpdateResponses];

export type EnvironmentsPromoteData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/environments/{slug}/promote';
};

export type EnvironmentsPromoteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type EnvironmentsPromoteError = EnvironmentsPromoteErrors[keyof EnvironmentsPromoteErrors];

export type EnvironmentsPromoteResponses = {
    /**
     * OK
     */
    200: EnvironmentDto;
};

export type EnvironmentsPromoteResponse = EnvironmentsPromoteResponses[keyof EnvironmentsPromoteResponses];

export type CreateEventData = {
    body: EventBodyWritable;
    headers?: {
        'x-axonpush-api-key'?: string;
        'x-api-key'?: string;
        'x-public-token'?: string;
        Authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/event';
};

export type CreateEventErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateEventError = CreateEventErrors[keyof CreateEventErrors];

export type CreateEventResponses = {
    /**
     * OK
     */
    200: EventOutputBody;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type EventsSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Window start (RFC3339); defaults to 24h before until
         */
        since?: string;
        /**
         * Window end (RFC3339); defaults to now
         */
        until?: string;
        /**
         * Max events to return (default 50, max 500)
         */
        limit?: number;
        /**
         * Filter by app
         */
        appId?: string;
        /**
         * Filter by channel
         */
        channelId?: string;
        /**
         * Filter by environment
         */
        environmentId?: string;
        /**
         * Filter by event type
         */
        eventType?: string;
        /**
         * Filter by source
         */
        source?: string;
        /**
         * Filter by status
         */
        status?: string;
        /**
         * Filter by trace id
         */
        traceId?: string;
        /**
         * Filter by agent id
         */
        agentId?: string;
        /**
         * Filter by agent name
         */
        agentName?: string;
        /**
         * Filter by tool name
         */
        toolName?: string;
        /**
         * Filter by semantic kind (agent, tool, llm, retriever, db, http, log)
         */
        semanticKind?: string;
        /**
         * Case-insensitive contains match on search text
         */
        q?: string;
        /**
         * JSONB attribute key for equality filter (paired with attrValue)
         */
        attrKey?: string;
        /**
         * JSONB attribute value for equality filter (paired with attrKey)
         */
        attrValue?: string;
    };
    url: '/events';
};

export type EventsSearchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type EventsSearchError = EventsSearchErrors[keyof EventsSearchErrors];

export type EventsSearchResponses = {
    /**
     * OK
     */
    200: SearchEventsOutputBody;
};

export type EventsSearchResponse = EventsSearchResponses[keyof EventsSearchResponses];

export type ExportListData = {
    body?: never;
    path?: never;
    query?: {
        envSlug?: string;
    };
    url: '/export-destinations';
};

export type ExportListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ExportListError = ExportListErrors[keyof ExportListErrors];

export type ExportListResponses = {
    /**
     * OK
     */
    200: ListOutputBody2;
};

export type ExportListResponse = ExportListResponses[keyof ExportListResponses];

export type ExportCreateData = {
    body: CreateInputBody2Writable;
    path?: never;
    query?: never;
    url: '/export-destinations';
};

export type ExportCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ExportCreateError = ExportCreateErrors[keyof ExportCreateErrors];

export type ExportCreateResponses = {
    /**
     * Created
     */
    201: DestinationDto;
};

export type ExportCreateResponse = ExportCreateResponses[keyof ExportCreateResponses];

export type ExportDeleteData = {
    body?: never;
    path: {
        destinationId: string;
    };
    query?: never;
    url: '/export-destinations/{destinationId}';
};

export type ExportDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ExportDeleteError = ExportDeleteErrors[keyof ExportDeleteErrors];

export type ExportDeleteResponses = {
    /**
     * OK
     */
    200: MessageOutputBody;
};

export type ExportDeleteResponse = ExportDeleteResponses[keyof ExportDeleteResponses];

export type ExportGetData = {
    body?: never;
    path: {
        destinationId: string;
    };
    query?: never;
    url: '/export-destinations/{destinationId}';
};

export type ExportGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ExportGetError = ExportGetErrors[keyof ExportGetErrors];

export type ExportGetResponses = {
    /**
     * OK
     */
    200: DestinationDto;
};

export type ExportGetResponse = ExportGetResponses[keyof ExportGetResponses];

export type ExportUpdateData = {
    body: UpdateInputBody2Writable;
    path: {
        destinationId: string;
    };
    query?: never;
    url: '/export-destinations/{destinationId}';
};

export type ExportUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ExportUpdateError = ExportUpdateErrors[keyof ExportUpdateErrors];

export type ExportUpdateResponses = {
    /**
     * OK
     */
    200: DestinationDto;
};

export type ExportUpdateResponse = ExportUpdateResponses[keyof ExportUpdateResponses];

export type FeatureFlagsMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/feature-flags/me';
};

export type FeatureFlagsMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type FeatureFlagsMeError = FeatureFlagsMeErrors[keyof FeatureFlagsMeErrors];

export type FeatureFlagsMeResponses = {
    /**
     * OK
     */
    200: FeatureFlags;
};

export type FeatureFlagsMeResponse = FeatureFlagsMeResponses[keyof FeatureFlagsMeResponses];

export type FeedbackCreateData = {
    body: CreateInputBody3Writable;
    headers?: {
        'CF-Connecting-IP'?: string;
        'X-Forwarded-For'?: string;
        'X-Real-IP'?: string;
    };
    path?: never;
    query?: never;
    url: '/feedback';
};

export type FeedbackCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type FeedbackCreateError = FeedbackCreateErrors[keyof FeedbackCreateErrors];

export type FeedbackCreateResponses = {
    /**
     * Created
     */
    201: CreateOutputBody;
};

export type FeedbackCreateResponse = FeedbackCreateResponses[keyof FeedbackCreateResponses];

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetHealthzError = GetHealthzErrors[keyof GetHealthzErrors];

export type GetHealthzResponses = {
    /**
     * OK
     */
    200: HealthOutputBody;
};

export type GetHealthzResponse = GetHealthzResponses[keyof GetHealthzResponses];

export type LicenseGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/license';
};

export type LicenseGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type LicenseGetError = LicenseGetErrors[keyof LicenseGetErrors];

export type LicenseGetResponses = {
    /**
     * OK
     */
    200: LicenseOutputBody;
};

export type LicenseGetResponse = LicenseGetResponses[keyof LicenseGetResponses];

export type ModerationEfficacyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Window start (RFC3339); defaults to 24h before until
         */
        since?: string;
        /**
         * Window end (RFC3339); defaults to now
         */
        until?: string;
    };
    url: '/moderation/efficacy';
};

export type ModerationEfficacyErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ModerationEfficacyError = ModerationEfficacyErrors[keyof ModerationEfficacyErrors];

export type ModerationEfficacyResponses = {
    /**
     * OK
     */
    200: EfficacyOutputBody;
};

export type ModerationEfficacyResponse = ModerationEfficacyResponses[keyof ModerationEfficacyResponses];

export type ModerationRulesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/moderation/rules';
};

export type ModerationRulesListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ModerationRulesListError = ModerationRulesListErrors[keyof ModerationRulesListErrors];

export type ModerationRulesListResponses = {
    /**
     * OK
     */
    200: ListRulesOutputBody;
};

export type ModerationRulesListResponse = ModerationRulesListResponses[keyof ModerationRulesListResponses];

export type ModerationRulesCreateData = {
    body: CreateRuleInputBodyWritable;
    path?: never;
    query?: never;
    url: '/moderation/rules';
};

export type ModerationRulesCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ModerationRulesCreateError = ModerationRulesCreateErrors[keyof ModerationRulesCreateErrors];

export type ModerationRulesCreateResponses = {
    /**
     * Created
     */
    201: RuleDto;
};

export type ModerationRulesCreateResponse = ModerationRulesCreateResponses[keyof ModerationRulesCreateResponses];

export type ModerationRulesDeleteData = {
    body?: never;
    path: {
        ruleId: string;
    };
    query?: never;
    url: '/moderation/rules/{ruleId}';
};

export type ModerationRulesDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ModerationRulesDeleteError = ModerationRulesDeleteErrors[keyof ModerationRulesDeleteErrors];

export type ModerationRulesDeleteResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type ModerationRulesDeleteResponse = ModerationRulesDeleteResponses[keyof ModerationRulesDeleteResponses];

export type ModerationViolationsListData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/moderation/violations';
};

export type ModerationViolationsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ModerationViolationsListError = ModerationViolationsListErrors[keyof ModerationViolationsListErrors];

export type ModerationViolationsListResponses = {
    /**
     * OK
     */
    200: ListViolationsOutputBody;
};

export type ModerationViolationsListResponse = ModerationViolationsListResponses[keyof ModerationViolationsListResponses];

export type OrganizationGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/organization';
};

export type OrganizationGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationGetError = OrganizationGetErrors[keyof OrganizationGetErrors];

export type OrganizationGetResponses = {
    /**
     * OK
     */
    200: OrganizationDto;
};

export type OrganizationGetResponse = OrganizationGetResponses[keyof OrganizationGetResponses];

export type OrganizationUpdateData = {
    body: UpdateOrganizationInputBodyWritable;
    path?: never;
    query?: never;
    url: '/organization';
};

export type OrganizationUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationUpdateError = OrganizationUpdateErrors[keyof OrganizationUpdateErrors];

export type OrganizationUpdateResponses = {
    /**
     * OK
     */
    200: OrganizationDto;
};

export type OrganizationUpdateResponse = OrganizationUpdateResponses[keyof OrganizationUpdateResponses];

export type OrganizationDeleteData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/organizations/{orgId}';
};

export type OrganizationDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationDeleteError = OrganizationDeleteErrors[keyof OrganizationDeleteErrors];

export type OrganizationDeleteResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type OrganizationDeleteResponse = OrganizationDeleteResponses[keyof OrganizationDeleteResponses];

export type OrganizationInvitationsListData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/invitations';
};

export type OrganizationInvitationsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationInvitationsListError = OrganizationInvitationsListErrors[keyof OrganizationInvitationsListErrors];

export type OrganizationInvitationsListResponses = {
    /**
     * OK
     */
    200: ListInvitationsOutputBody;
};

export type OrganizationInvitationsListResponse = OrganizationInvitationsListResponses[keyof OrganizationInvitationsListResponses];

export type OrganizationInvitationsCreateData = {
    body: CreateInvitationInputBodyWritable;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/invitations';
};

export type OrganizationInvitationsCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationInvitationsCreateError = OrganizationInvitationsCreateErrors[keyof OrganizationInvitationsCreateErrors];

export type OrganizationInvitationsCreateResponses = {
    /**
     * Created
     */
    201: InvitationDto;
};

export type OrganizationInvitationsCreateResponse = OrganizationInvitationsCreateResponses[keyof OrganizationInvitationsCreateResponses];

export type OrganizationInvitationsCancelData = {
    body?: never;
    path: {
        orgId: string;
        invitationId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/invitations/{invitationId}';
};

export type OrganizationInvitationsCancelErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationInvitationsCancelError = OrganizationInvitationsCancelErrors[keyof OrganizationInvitationsCancelErrors];

export type OrganizationInvitationsCancelResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type OrganizationInvitationsCancelResponse = OrganizationInvitationsCancelResponses[keyof OrganizationInvitationsCancelResponses];

export type OrganizationMembersListData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/members';
};

export type OrganizationMembersListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationMembersListError = OrganizationMembersListErrors[keyof OrganizationMembersListErrors];

export type OrganizationMembersListResponses = {
    /**
     * OK
     */
    200: ListMembersOutputBody;
};

export type OrganizationMembersListResponse = OrganizationMembersListResponses[keyof OrganizationMembersListResponses];

export type OrganizationMembersRemoveData = {
    body?: never;
    path: {
        orgId: string;
        userId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/members/{userId}';
};

export type OrganizationMembersRemoveErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationMembersRemoveError = OrganizationMembersRemoveErrors[keyof OrganizationMembersRemoveErrors];

export type OrganizationMembersRemoveResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type OrganizationMembersRemoveResponse = OrganizationMembersRemoveResponses[keyof OrganizationMembersRemoveResponses];

export type OrganizationMembersUpdateRoleData = {
    body: UpdateMemberRoleInputBodyWritable;
    path: {
        orgId: string;
        userId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/members/{userId}';
};

export type OrganizationMembersUpdateRoleErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationMembersUpdateRoleError = OrganizationMembersUpdateRoleErrors[keyof OrganizationMembersUpdateRoleErrors];

export type OrganizationMembersUpdateRoleResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type OrganizationMembersUpdateRoleResponse = OrganizationMembersUpdateRoleResponses[keyof OrganizationMembersUpdateRoleResponses];

export type OrganizationTelemetryPolicyGetData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/telemetry-policy';
};

export type OrganizationTelemetryPolicyGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationTelemetryPolicyGetError = OrganizationTelemetryPolicyGetErrors[keyof OrganizationTelemetryPolicyGetErrors];

export type OrganizationTelemetryPolicyGetResponses = {
    /**
     * OK
     */
    200: TelemetryPolicyOutputBody;
};

export type OrganizationTelemetryPolicyGetResponse = OrganizationTelemetryPolicyGetResponses[keyof OrganizationTelemetryPolicyGetResponses];

export type OrganizationTelemetryPolicyUpdateData = {
    /**
     * Telemetry policy JSON object
     */
    body: unknown;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/telemetry-policy';
};

export type OrganizationTelemetryPolicyUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationTelemetryPolicyUpdateError = OrganizationTelemetryPolicyUpdateErrors[keyof OrganizationTelemetryPolicyUpdateErrors];

export type OrganizationTelemetryPolicyUpdateResponses = {
    /**
     * OK
     */
    200: TelemetryPolicyOutputBody;
};

export type OrganizationTelemetryPolicyUpdateResponse = OrganizationTelemetryPolicyUpdateResponses[keyof OrganizationTelemetryPolicyUpdateResponses];

export type OrganizationTransferOwnershipData = {
    body: TransferOwnershipInputBodyWritable;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/transfer-ownership';
};

export type OrganizationTransferOwnershipErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type OrganizationTransferOwnershipError = OrganizationTransferOwnershipErrors[keyof OrganizationTransferOwnershipErrors];

export type OrganizationTransferOwnershipResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type OrganizationTransferOwnershipResponse = OrganizationTransferOwnershipResponses[keyof OrganizationTransferOwnershipResponses];

export type TokensListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public-ingest-tokens';
};

export type TokensListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TokensListError = TokensListErrors[keyof TokensListErrors];

export type TokensListResponses = {
    /**
     * OK
     */
    200: ListTokensOutputBody;
};

export type TokensListResponse = TokensListResponses[keyof TokensListResponses];

export type TokensCreateData = {
    body: CreateTokenInputBodyWritable;
    path?: never;
    query?: never;
    url: '/public-ingest-tokens';
};

export type TokensCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TokensCreateError = TokensCreateErrors[keyof TokensCreateErrors];

export type TokensCreateResponses = {
    /**
     * Created
     */
    201: CreateTokenOutputBody;
};

export type TokensCreateResponse = TokensCreateResponses[keyof TokensCreateResponses];

export type TokensRevokeData = {
    body?: never;
    path: {
        tokenId: string;
    };
    query?: never;
    url: '/public-ingest-tokens/{tokenId}';
};

export type TokensRevokeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TokensRevokeError = TokensRevokeErrors[keyof TokensRevokeErrors];

export type TokensRevokeResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type TokensRevokeResponse = TokensRevokeResponses[keyof TokensRevokeResponses];

export type TracesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Window start (RFC3339); defaults to 24h before until
         */
        since?: string;
        /**
         * Window end (RFC3339); defaults to now
         */
        until?: string;
        /**
         * Max traces to return (default 50, max 500)
         */
        limit?: number;
        /**
         * Rows to skip for paging
         */
        offset?: number;
    };
    url: '/traces';
};

export type TracesListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TracesListError = TracesListErrors[keyof TracesListErrors];

export type TracesListResponses = {
    /**
     * OK
     */
    200: ListTracesOutputBody;
};

export type TracesListResponse = TracesListResponses[keyof TracesListResponses];

export type TracesGetData = {
    body?: never;
    path: {
        traceId: string;
    };
    query?: never;
    url: '/traces/{traceId}';
};

export type TracesGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type TracesGetError = TracesGetErrors[keyof TracesGetErrors];

export type TracesGetResponses = {
    /**
     * OK
     */
    200: GetTraceOutputBody;
};

export type TracesGetResponse = TracesGetResponses[keyof TracesGetResponses];

export type UserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type UserMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UserMeError = UserMeErrors[keyof UserMeErrors];

export type UserMeResponses = {
    /**
     * OK
     */
    200: MeDto;
};

export type UserMeResponse = UserMeResponses[keyof UserMeResponses];

export type UserMeUpdateData = {
    body: UpdateProfileInputBodyWritable;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UserMeUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UserMeUpdateError = UserMeUpdateErrors[keyof UserMeUpdateErrors];

export type UserMeUpdateResponses = {
    /**
     * OK
     */
    200: MeDto;
};

export type UserMeUpdateResponse = UserMeUpdateResponses[keyof UserMeUpdateResponses];

export type UserMeSetActiveOrgData = {
    body: SetActiveOrgInputBodyWritable;
    path?: never;
    query?: never;
    url: '/users/me/active-org';
};

export type UserMeSetActiveOrgErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UserMeSetActiveOrgError = UserMeSetActiveOrgErrors[keyof UserMeSetActiveOrgErrors];

export type UserMeSetActiveOrgResponses = {
    /**
     * OK
     */
    200: OkOutputBody;
};

export type UserMeSetActiveOrgResponse = UserMeSetActiveOrgResponses[keyof UserMeSetActiveOrgResponses];

export type UserMeOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/organizations';
};

export type UserMeOrganizationsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UserMeOrganizationsError = UserMeOrganizationsErrors[keyof UserMeOrganizationsErrors];

export type UserMeOrganizationsResponses = {
    /**
     * OK
     */
    200: UserOrgsOutputBody;
};

export type UserMeOrganizationsResponse = UserMeOrganizationsResponses[keyof UserMeOrganizationsResponses];

export type AlertsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/alerts';
};

export type AlertsListErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AlertsListError = AlertsListErrors[keyof AlertsListErrors];

export type AlertsListResponses = {
    /**
     * OK
     */
    200: ListOutputBody1;
};

export type AlertsListResponse = AlertsListResponses[keyof AlertsListResponses];

export type AlertsCreateData = {
    body: CreateInputBody1Writable;
    path?: never;
    query?: never;
    url: '/v2/alerts';
};

export type AlertsCreateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AlertsCreateError = AlertsCreateErrors[keyof AlertsCreateErrors];

export type AlertsCreateResponses = {
    /**
     * Created
     */
    201: AlertRuleDto;
};

export type AlertsCreateResponse = AlertsCreateResponses[keyof AlertsCreateResponses];

export type AlertsDeleteData = {
    body?: never;
    path: {
        alertRuleId: string;
    };
    query?: never;
    url: '/v2/alerts/{alertRuleId}';
};

export type AlertsDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AlertsDeleteError = AlertsDeleteErrors[keyof AlertsDeleteErrors];

export type AlertsDeleteResponses = {
    /**
     * OK
     */
    200: DeleteOutputBody;
};

export type AlertsDeleteResponse = AlertsDeleteResponses[keyof AlertsDeleteResponses];

export type AlertsUpdateData = {
    body: UpdateInputBody1Writable;
    path: {
        alertRuleId: string;
    };
    query?: never;
    url: '/v2/alerts/{alertRuleId}';
};

export type AlertsUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AlertsUpdateError = AlertsUpdateErrors[keyof AlertsUpdateErrors];

export type AlertsUpdateResponses = {
    /**
     * OK
     */
    200: AlertRuleDto;
};

export type AlertsUpdateResponse = AlertsUpdateResponses[keyof AlertsUpdateResponses];

export type WebhooksListDeliveriesData = {
    body?: never;
    path: {
        endpointId: string;
    };
    query?: never;
    url: '/webhooks/deliveries/{endpointId}';
};

export type WebhooksListDeliveriesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type WebhooksListDeliveriesError = WebhooksListDeliveriesErrors[keyof WebhooksListDeliveriesErrors];

export type WebhooksListDeliveriesResponses = {
    /**
     * OK
     */
    200: ListDeliveriesOutputBody;
};

export type WebhooksListDeliveriesResponse = WebhooksListDeliveriesResponses[keyof WebhooksListDeliveriesResponses];

export type WebhooksCreateEndpointData = {
    body: CreateEndpointInputBodyWritable;
    path?: never;
    query?: never;
    url: '/webhooks/endpoints';
};

export type WebhooksCreateEndpointErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type WebhooksCreateEndpointError = WebhooksCreateEndpointErrors[keyof WebhooksCreateEndpointErrors];

export type WebhooksCreateEndpointResponses = {
    /**
     * Created
     */
    201: CreateEndpointOutputBody;
};

export type WebhooksCreateEndpointResponse = WebhooksCreateEndpointResponses[keyof WebhooksCreateEndpointResponses];

export type WebhooksListEndpointsData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/webhooks/endpoints/channel/{channelId}';
};

export type WebhooksListEndpointsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type WebhooksListEndpointsError = WebhooksListEndpointsErrors[keyof WebhooksListEndpointsErrors];

export type WebhooksListEndpointsResponses = {
    /**
     * OK
     */
    200: ListEndpointsOutputBody;
};

export type WebhooksListEndpointsResponse = WebhooksListEndpointsResponses[keyof WebhooksListEndpointsResponses];

export type WebhooksDeleteEndpointData = {
    body?: never;
    path: {
        endpointId: string;
    };
    query?: never;
    url: '/webhooks/endpoints/{endpointId}';
};

export type WebhooksDeleteEndpointErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type WebhooksDeleteEndpointError = WebhooksDeleteEndpointErrors[keyof WebhooksDeleteEndpointErrors];

export type WebhooksDeleteEndpointResponses = {
    /**
     * OK
     */
    200: MessageOutputBody;
};

export type WebhooksDeleteEndpointResponse = WebhooksDeleteEndpointResponses[keyof WebhooksDeleteEndpointResponses];
