"""Regression test for declared-vs-imported runtime dependencies.

Catches the class of bug where an autogenerated module (e.g. the
openapi-python-client output under ``src/axonpush/_internal/api``)
top-level-imports a third-party package that isn't listed in
``[project].dependencies`` of ``pyproject.toml``. That kind of miss
is invisible in the dev venv (CI installs ``--extra all``, which pulls
the package in transitively) and only blows up for end users on a
``pip install axonpush`` clean install.

Strategy:

1. Walk every ``.py`` under ``src/axonpush`` other than the integration
   files explicitly gated behind an extra.
2. AST-parse and collect top-level absolute imports — the imports that
   run at module load time.
3. Assert each top-level package is one of:
   - the Python stdlib,
   - the SDK itself (``axonpush``),
   - a name listed in ``[project].dependencies``.

If a future codegen pass starts importing, say, ``orjson`` or
``yaml`` at module top level, this test fails before release instead
of in a user's terminal.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib  # type: ignore[no-redef]

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = REPO_ROOT / "src" / "axonpush"


# Files that legitimately import a third-party dep gated behind an extra.
# Each entry is the path relative to ``src/axonpush``. These are skipped
# by the audit because the dep is declared under
# ``[project.optional-dependencies]``, not the base list.
EXTRA_GATED_FILES: set[str] = {
    "integrations/anthropic.py",
    "integrations/crewai.py",
    "integrations/deepagents.py",
    "integrations/langchain.py",
    "integrations/loguru.py",
    "integrations/openai_agents.py",
    "integrations/otel.py",
    "integrations/sentry.py",
    "integrations/structlog.py",
}


# Mapping of import name → distribution name. ``import dateutil`` comes
# from the ``python-dateutil`` distribution; ``import pydantic_settings``
# comes from the ``pydantic-settings`` distribution; etc. PEP 503
# normalises hyphens/underscores both ways, so we normalise to compare.
def _normalize(name: str) -> str:
    return name.lower().replace("_", "-")


IMPORT_NAME_TO_DIST = {
    "dateutil": "python-dateutil",
    "paho": "paho-mqtt",
    "pydantic_settings": "pydantic-settings",
    "yaml": "pyyaml",
}


def _toplevel_imports(path: Path) -> set[str]:
    """Return the set of top-level absolute import root packages in ``path``.

    Only collects imports that execute at module load time — imports
    nested inside ``def`` / ``if`` / ``try`` blocks are skipped because
    those are deliberately lazy and are guarded by their callers.
    """
    tree = ast.parse(path.read_text())
    roots: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.Import):
            for n in node.names:
                roots.add(n.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            if node.level == 0 and node.module:
                roots.add(node.module.split(".")[0])
    return roots


def _declared_runtime_dists() -> set[str]:
    """Distributions listed in ``[project].dependencies`` (PEP 621)."""
    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text())
    deps = pyproject["project"]["dependencies"]
    out: set[str] = set()
    for spec in deps:
        # Strip extras + version specifiers. "httpx>=0.25.0,<1.0" -> "httpx".
        head = spec.split(";", 1)[0].strip()
        for sep in ("<", ">", "=", "!", "~", "[", " "):
            head = head.split(sep, 1)[0]
        out.add(_normalize(head))
    return out


def test_top_level_imports_are_all_declared() -> None:
    """Every top-level import in non-extra files must resolve to a declared runtime dep."""
    declared = _declared_runtime_dists()
    stdlib = set(sys.stdlib_module_names) | {
        # Vendored / always-available helpers shipped with typing
        "typing_extensions",
    }

    offenders: list[tuple[str, str]] = []
    for py in sorted(SRC.rglob("*.py")):
        rel = py.relative_to(SRC).as_posix()
        if rel in EXTRA_GATED_FILES:
            continue
        for top in _toplevel_imports(py):
            if top in stdlib:
                continue
            if top == "axonpush":
                continue
            dist = IMPORT_NAME_TO_DIST.get(top, top)
            if _normalize(dist) in declared:
                continue
            offenders.append((rel, f"{top} (dist: {dist})"))

    assert not offenders, (
        "Top-level imports in src/axonpush are not declared as runtime dependencies "
        "in pyproject.toml. This will cause `pip install axonpush` to fail at import "
        "time on a clean venv. Either declare the dep, gate the import behind an "
        "extra (and add the file to EXTRA_GATED_FILES), or move the import inside "
        "a function so it's lazy.\n\nOffenders:\n  "
        + "\n  ".join(f"{path}: {dep}" for path, dep in offenders)
    )
