"""Generate typed operations resource facades and .NET DTOs from the server contract.

Run after the standard TS/Python OpenAPI generators. No server is required.
The generated resource layer only forwards typed requests through the existing
per-client transport, preserving the contract's pagination and receipt envelopes.
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = json.loads((ROOT / "contract/openapi.sdk.json").read_text())
schemas = spec["components"]["schemas"]
groups = {"workspaces": "Workspaces", "templates": "Templates", "observations": "Observations", "activity": "Activity"}
ops: dict[str, list[dict]] = {g: [] for g in groups}


def snake(s: str) -> str:
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", s)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).replace(".", "_").replace("-", "_").lower()


def camel(s: str) -> str:
    chunks = snake(s).split("_")
    return chunks[0] + "".join(c.title() for c in chunks[1:])


def pascal(s: str) -> str:
    c = camel(s.replace("$", ""))
    return c[0].upper() + c[1:]


def ref(s: dict) -> str | None:
    return s.get("$ref", "").rsplit("/", 1)[-1] or None


for path, item in spec["paths"].items():
    for verb, operation in item.items():
        if verb not in ("get", "post", "put", "patch", "delete"):
            continue
        oid = operation.get("operationId", "")
        group = oid.split(".")[0]
        if group not in groups:
            continue
        body = operation.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema", {})
        responses = [r for code, r in operation["responses"].items() if code.startswith("2")]
        response = responses[0].get("content", {}).get("application/json", {}).get("schema", {})
        body_required = operation.get("requestBody", {}).get("required", False)
        ops[group].append(dict(oid=oid, path=path, verb=verb, name=oid.split(".")[-1], body=ref(body), body_required=body_required, response=ref(response), params=operation.get("parameters", []), tag=operation["tags"][0], summary=operation.get("summary", "")))

for group, cls in groups.items():
    operations = ops[group]
    if not operations:
        raise SystemExit(f"Missing operations group {group}")
    types = sorted({x[k] for x in operations for k in ("body", "response") if x[k]})
    data_types = [pascal(x["oid"]) + "Data" for x in operations if any(p["in"] == "query" for p in x["params"])]
    ts = ['// Generated by tools/generate-operations.py. Regenerate from the server contract.', 'import { ' + ', '.join(camel(x["oid"]) for x in operations) + ' } from "../_internal/api/sdk.gen.js";', 'import type { ' + ', '.join(types + data_types) + ' } from "../_internal/api/types.gen.js";', 'import type { ResourceClient } from "./_client.js";', '', f'export class {cls}Resource {{', '  constructor(private readonly client: ResourceClient) {}']
    py = ['"""Generated typed operations facade; regenerate with tools/generate-operations.py."""', 'from __future__ import annotations', 'from collections.abc import Mapping', 'from typing import Any, TYPE_CHECKING', 'from axonpush._internal.api.models import (', *('    ' + t + ',' for t in types), ')', *(['from axonpush._internal.api.types import UNSET, Unset'] if any(x["body"] and not x["body_required"] for x in operations) else []), 'if TYPE_CHECKING:', '    from axonpush.resources._base import AsyncClientProtocol, SyncClientProtocol']
    for x in operations:
        # Tags can differ inside a resource (observation accept and receipt).
        module = snake(x["oid"])
        dirs = list((ROOT / 'packages/python/src/axonpush/_internal/api/api').glob('*/' + module + '.py'))
        if len(dirs) != 1:
            raise SystemExit(f'Cannot resolve generated Python operation {module}')
        py.append(f'from axonpush._internal.api.api.{dirs[0].parent.name} import {module} as _{snake(x["name"])}_op')
    for x in operations:
        params = [p for p in x["params"] if p["in"] == "path"]
        queries = [p for p in x["params"] if p["in"] == "query"]
        args = [p["name"] + ': string' for p in params]
        call = ['path: { ' + ', '.join(p["name"] for p in params) + ' }'] if params else []
        if x["body"]:
            args.append(('body: ' if x["body_required"] else 'body?: ') + x["body"])
            call.append('body')
        if queries:
            args.append('query: ' + pascal(x["oid"]) + 'Data["query"] = {}')
            call.append('query')
        ts += ['', '  /** ' + x['summary'] + f'. `{x["verb"].upper()} {x["path"]}` */', f'  async {x["name"]}({", ".join(args)}): Promise<{x["response"] or "unknown"} | null> {{', f'    return this.client.invoke({camel(x["oid"])}, {{ {", ".join(call)} }});', '  }']
    ts += ['}', '']
    for asynchronous in (False, True):
        py += ['', '', 'class ' + ('Async' if asynchronous else '') + cls + ':', '    def __init__(self, client: ' + ('AsyncClientProtocol' if asynchronous else 'SyncClientProtocol') + ') -> None:', '        self._client = client']
        for x in operations:
            params = [p for p in x["params"] if p["in"] == "path"]
            queries = [p for p in x["params"] if p["in"] == "query"]
            args = ['self'] + [snake(p["name"]) + ': str' for p in params]
            call = [snake(p["name"]) + '=' + snake(p["name"]) for p in params]
            if x["body"]:
                args.append('body: ' + x["body"] + ('' if x["body_required"] else ' | Unset = UNSET'))
                call.append('body=body')
            if queries:
                args.append('params: Mapping[str, Any] | None = None')
                call.append('**{k: v for k, v in (params or {}).items() if v is not None}')
            py += ['', f'    {"async " if asynchronous else ""}def {snake(x["name"])}({", ".join(args)}) -> {x["response"] or "Any"} | None:', '        """' + x['summary'] + '."""', f'        return {"await " if asynchronous else ""}self._client._invoke(_{snake(x["name"])}_op{", " if call else ""}{", ".join(call)})']
    (ROOT / f'packages/typescript/src/resources/{group}.ts').write_text('\n'.join(ts))
    (ROOT / f'packages/python/src/axonpush/resources/{group}.py').write_text('\n'.join(py) + '\n')

# .NET has no general generated OpenAPI client. Emit just this shared operations
# graph; explicit JSON names prevent camel/snake casing drift across languages.
dotnet = ROOT / 'packages/dotnet/src/AxonPush/Operations'
dotnet.mkdir(exist_ok=True)
needed: set[str] = set()


def visit_schema(value: object) -> None:
    if isinstance(value, dict):
        name = ref(value)
        if name and name not in needed:
            needed.add(name)
            visit_schema(schemas[name])
        for v in value.values():
            visit_schema(v)
    elif isinstance(value, list):
        for v in value:
            visit_schema(v)


for values in ops.values():
    for x in values:
        for k in ('body', 'response'):
            if x[k]:
                visit_schema({'$ref': '#/components/schemas/' + x[k]})


def cs_type(s: dict) -> str:
    if ref(s):
        return ref(s)  # type: ignore[return-value]
    if isinstance(s.get('type'), list):
        types = [t for t in s['type'] if t != 'null']
        if len(types) == 1:
            return cs_type({**s, 'type': types[0]})
    if 'anyOf' in s:
        variants = [v for v in s['anyOf'] if v.get('type') != 'null']
        if len(variants) == 1:
            return cs_type(variants[0])
    typ = s.get('type')
    if typ == 'array':
        return 'IReadOnlyList<' + cs_type(s['items']) + '>'
    if typ == 'object':
        additional = s.get('additionalProperties')
        if isinstance(additional, dict):
            return 'IReadOnlyDictionary<string, ' + cs_type(additional) + '>'
        return 'JsonElement'
    if typ == 'integer':
        return 'long'
    if typ == 'number':
        return 'double'
    if typ == 'boolean':
        return 'bool'
    if typ == 'string':
        return 'DateTimeOffset' if s.get('format') == 'date-time' else 'string'
    return 'JsonElement'


CS_KEYWORDS = {'ref', 'out', 'in', 'params', 'object', 'string', 'event', 'base', 'class', 'default', 'namespace', 'operator', 'checked', 'fixed', 'lock', 'is', 'as', 'new', 'this', 'value'}


def cs_ident(name: str) -> str:
    return '@' + name if name in CS_KEYWORDS else name


header = '// Generated by tools/generate-operations.py. Do not edit manually.\n#nullable enable\n'
models = [header, 'using System.Text.Json;', 'using System.Text.Json.Serialization;', '', 'namespace AxonPush.Operations;', '']
for name in sorted(needed):
    s = schemas[name]
    if s.get('type') != 'object' or not s.get('properties'):
        # Alias schemas with arbitrary properties cannot be records.
        continue
    models += ['public sealed record ' + name, '{']
    required = set(s.get('required', []))
    for prop, prop_schema in s['properties'].items():
        if prop == "$schema":
            continue
        typ = cs_type(prop_schema)
        is_required = prop in required
        default = ' = default!;' if is_required and typ not in ('long', 'double', 'bool', 'DateTimeOffset', 'JsonElement') else ''
        nullable = not is_required or (isinstance(prop_schema.get('type'), list) and 'null' in prop_schema['type']) or any(v.get('type') == 'null' for v in prop_schema.get('anyOf', []))
        models += ['    [JsonPropertyName(' + json.dumps(prop) + ')]', '    public ' + typ + ('?' if nullable else '') + ' ' + pascal(prop) + ' { get; init; }' + default]
    models += ['}', '']
(dotnet / 'Models.g.cs').write_text('\n'.join(models))
for group, cls in groups.items():
    lines = [header, 'using System.Globalization;', 'using AxonPush.Internal;', '', 'namespace AxonPush.Operations;', '', 'public sealed class ' + cls + 'Resource', '{', '    private readonly AxonPushTransport _transport;', '    internal ' + cls + 'Resource(AxonPushTransport transport) => _transport = transport;']
    for x in ops[group]:
        params = [p for p in x['params'] if p['in'] == 'path']
        queries = [p for p in x['params'] if p['in'] == 'query']
        args = ['string ' + p['name'] for p in params]
        if x['body']:
            args.append(x['body'] + (' body' if x['body_required'] else '? body = null'))
        for q in queries:
            args.append(cs_type(q.get('schema', {})) + '? ' + cs_ident(q['name']) + ' = null')
        args.append('CancellationToken cancellationToken = default')
        path = x['path'].lstrip('/')
        for p in params:
            path = path.replace('{' + p['name'] + '}', '{Uri.EscapeDataString(' + p['name'] + ')}')
        lines += ['', '    /// <summary>' + x['summary'] + '.</summary>', '    public Task<' + (x['response'] or 'object') + '?> ' + pascal(x['name']) + 'Async(' + ', '.join(args) + ')', '    {', '        var path = $"' + path + '";']
        for q in queries:
            lines.append('        path = AddQuery(path, "' + q['name'] + '", ' + cs_ident(q['name']) + ');')
        sender = 'SendObservationAsync' if x['oid'] == 'observations.accept' else 'SendAsync'
        lines += ['        return _transport.' + sender + '<' + (x['response'] or 'object') + '>(HttpMethod.' + x['verb'].title() + ', path, ' + ('body' if x['body'] else 'null') + ', cancellationToken);', '    }']
    lines += ['', '    private static string AddQuery(string path, string key, object? value)', '    {', '        if (value is null) return path;', '        var text = Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty;', '        return path + (path.Contains(\'?\') ? "&" : "?") + Uri.EscapeDataString(key) + "=" + Uri.EscapeDataString(text);', '    }', '}', '']
    (dotnet / (cls + 'Resource.g.cs')).write_text('\n'.join(lines))
print(f'Generated {sum(map(len, ops.values()))} operations for Python, TypeScript and .NET')

subprocess.run(["bun", "--no-env-file", "x", "biome", "check", "--write", *[f"packages/typescript/src/resources/{g}.ts" for g in groups]], cwd=ROOT, check=True)
python_paths = [f"src/axonpush/resources/{g}.py" for g in groups]
subprocess.run(["uv", "run", "ruff", "check", "--fix", *python_paths], cwd=ROOT / "packages/python", check=True)
subprocess.run(["uv", "run", "ruff", "format", *python_paths], cwd=ROOT / "packages/python", check=True)
